import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const q = (prompt, options, correct, explanation) => [prompt, options, correct, explanation];

function c(id, title, subtitle, difficulty, minutes, prereqs, summary, analogy, bullets, terms, vizSteps, realTitle, realStory, takeaway, quizzes, interactive, code) {
  return [id, title, subtitle, difficulty, minutes, prereqs, summary, analogy, bullets, terms, vizSteps, realTitle, realStory, takeaway, quizzes, interactive, code].filter((x) => x !== undefined);
}

const toggle = (options, insights) => ['toggle', options, insights];

const seeds = {
  'how-llms-work': [
    c('tokenization','Tokenization','Split text into model-readable pieces','beginner',8,[],
      'Tokenization converts text into tokens—integer IDs the model understands. Tokens may be words, subwords, or characters depending on the tokenizer. Everything an LLM reads or writes is mediated by this segmentation, which affects cost, context limits, and awkward splits of rare words.',
      'Like cutting a paragraph into LEGO bricks before a machine rebuilds meaning from brick IDs.',
      ['Tokenizers map text to token ID sequences and back.','Subword schemes balance vocabulary size and coverage.','Token counts drive context usage and pricing.','Weird splits can hurt reasoning on codes, names, or math.'],
      [['Token','Atomic text unit for the model'],['Tokenizer','Algorithm mapping text to token IDs'],['Subword','Fragment smaller than a full word']],
      ['Raw sentence arrives.','Tokenizer applies merge rules.','Produce token strings.','Map to numeric IDs.','IDs enter the embedding layer.'],
      'API billing by tokens','A verbose prompt costs more even if word count looks modest.','Measure tokens, not only words.',
      [q('Tokenization turns text into…',['Pixels only','Token IDs','CSS classes','IP addresses'],1,'IDs the model consumes.'),q('Subword tokenization helps…',['Delete GPUs','Handle rare words with fragments','Remove attention','Ban Unicode'],1,'Fragments compose unknowns.'),q('Token count affects…',['Only wallpaper','Context limits and often pricing','Ocean tides','Mouse DPI'],1,'Context and cost.')],
      ['token-split']),
    c('vocabulary-context-window','Vocabulary & Context Window','What the model can name, and how much it can see','beginner',7,['tokenization'],
      'Vocabulary is the finite set of tokens a model knows IDs for. The context window is how many tokens of prompt, history, and generation the model can consider at once. If information falls outside the window, the model cannot directly use it unless you retrieve or summarize it back in.',
      'Vocabulary is the dictionary of bricks; context window is the size of the table you can build on.',
      ['Finite vocab plus subword strategies cover open text.','Context window is a hard capacity constraint.','Long context helps but is not perfect memory.','Attention cost scales with context length.'],
      [['Vocabulary','Set of known tokens'],['Context window','Max tokens per model pass'],['Truncation','Dropping overflow tokens']],
      ['Prompt grows with chat history.','Tokenizer counts tokens.','Nearing the window limit.','Oldest turns get truncated or summarized.','Model only sees what remains.'],
      'Support chat resets','Agents summarize old turns to stay inside context.','Long conversations need memory strategies.',
      [q('If text exceeds context…',['Model telepathically knows it','It must be truncated, summarized, or retrieved later','RAM upgrades itself','CSS expands'],1,'Outside window is invisible.'),q('Vocabulary is…',['Infinite always','Finite token inventory','A Kubernetes pod','A color palette'],1,'Finite token set.'),q('Longer context always means perfect recall.',['True','False','Only at night','Only in Python'],1,'Capacity is not perfect memory.')],
      toggle(['Short FAQ answer','Paste entire codebase','Summarize then ask'],{'Short FAQ answer':'Usually fits easily.','Paste entire codebase':'May blow the window; chunk/retrieve instead.','Summarize then ask':'Practical context engineering.'})),
    c('embeddings','Embeddings','Meaning as coordinates in vector space','intermediate',9,['vocabulary-context-window'],
      'Embeddings are numeric vectors representing tokens, sentences, or documents so similar meanings land nearby geometrically. Models use embeddings internally; retrieval systems also embed queries and docs to find neighbors. Distances become a proxy for semantic relatedness.',
      'A city map for meaning: doctor sits nearer nurse than screwdriver.',
      ['Embedding layer maps token IDs to vectors.','Training places related items closer.','Cosine similarity is a common closeness measure.','Dimensionality and data shape the geometry.'],
      [['Embedding','Vector representing meaning'],['Vector space','Coordinate world for similarity'],['Cosine similarity','Angle-based closeness score']],
      ['Token IDs enter.','Lookup embedding vectors.','Nearby meanings cluster.','Downstream layers transform vectors.','Similarity search can reuse embeddings.'],
      'Duplicate question detection','Forums embed posts to find near-duplicate asks.','Vectors power semantic matching.',
      [q('Embeddings represent…',['Only file sizes','Meaning as vectors','CSS breakpoints','MAC addresses'],1,'Vectors for meaning.'),q('Similar meanings should be…',['Far apart','Nearby in vector space','Deleted','Sorted alphabetically only'],1,'Geometry encodes similarity.'),q('Cosine similarity measures…',['Exact string equality only','Directional closeness of vectors','CPU temperature','Packet loss'],1,'Common semantic metric.')],
      ['similarity']),
    c('positional-encoding','Positional Encoding','Tell the model token order matters','intermediate',8,['embeddings'],
      'Self-attention alone does not inherently know order. Positional encodings (sinusoidal, learned, RoPE, ALiBi, and others) inject order so “dog bites man” differs from “man bites dog.”',
      'Like page numbers in a shuffled manuscript—bricks need positions to rebuild the plot.',
      ['Attention mixes tokens; positions disambiguate order.','Absolute and relative schemes exist.','Modern LLMs often use rotary embeddings (RoPE).','Length generalization depends on the scheme.'],
      [['Positional encoding','Signal carrying sequence order'],['RoPE','Rotary position embedding used in many LLMs'],['Relative position','Encoding distances between tokens']],
      ['Tokens without order look bag-of-words-ish.','Add position signals to embeddings.','Attention uses order-aware interactions.','Sentence meaning stabilizes.','Long-context behavior depends on the method.'],
      'Code completion sensitivity','Swapping two args changes meaning; positions preserve that.','Order is semantics in language and code.',
      [q('Without positions, transformers risk…',['Perfect grammar always','Losing word-order information','Faster DNS','Bigger monitors'],1,'Order must be injected.'),q('RoPE is…',['A climbing sport only','A positional method used in many LLMs','A database','A CSS unit'],1,'Rotary positions.'),q('Dog bites man vs man bites dog shows…',['Positions do not matter','Order changes meaning','Tokens are pixels','Models ignore verbs'],1,'Order encodes meaning.')],
      toggle(['Bag embeddings only','Embeddings + positions','Shuffle tokens at inference'],{'Bag embeddings only':'Weak order signal.','Embeddings + positions':'Standard fix.','Shuffle tokens at inference':'Breaks meaning on purpose.'})),
    c('self-attention','Self-Attention','Each token gathers relevant context from others','intermediate',10,['positional-encoding'],
      'Self-attention lets every token build a new representation by taking a weighted mix of other tokens information. Weights come from compatibility between queries and keys; values carry the content mixed in. This is how context disambiguates words like bank.',
      'In a meeting, you glance more at people relevant to your current sentence—not equally at everyone forever.',
      ['Query, Key, Value projections create attention scores.','Softmax turns scores into weights.','Weighted values form the output.','Causal masks prevent looking ahead in decoders.','Attention is powerful but quadratic in sequence length.'],
      [['Query','What I am looking for'],['Key','What I contain for matching'],['Value','Information I contribute when selected']],
      ['Each token makes Q, K, V.','Score Q against all K.','Softmax yields attention weights.','Mix V by those weights.','New contextual vectors appear.'],
      'Pronoun resolution','Attention helps bind pronouns to the right noun.','Context selection is core to understanding.',
      [q('Self-attention mainly…',['Sorts files','Lets tokens gather info from other tokens','Charges laptops','Paints UI'],1,'Contextual mixing.'),q('Softmax over scores produces…',['Random bytes','Attention weights','IP leases','PDF fonts'],1,'Weights sum to about 1.'),q('Causal masking stops…',['All learning','Looking at future tokens while decoding','Using GPUs','Saving logs'],1,'No peeking ahead.')],
      toggle(['river bank erosion','bank account balance'],{'river bank erosion':'Finance senses downweighted.','bank account balance':'River senses downweighted.'})),
    c('multi-head-attention','Multi-Head Attention','Several attention perspectives in parallel','intermediate',8,['self-attention'],
      'Multi-head attention runs several attention operations in parallel, each potentially specializing in different relationship types, then concatenates results. More heads increase expressive capacity at a compute cost.',
      'Multiple specialists reading the same paragraph: one tracks subjects, one tracks numbers, one tracks quotes.',
      ['Split Q/K/V into heads.','Each head attends independently.','Concatenate head outputs.','Project back to model dimension.','Heads can specialize but are not guaranteed interpretable.'],
      [['Attention head','One parallel attention subspace'],['Model dimension','Width of token vectors'],['Concatenation','Joining head outputs']],
      ['Start with token vectors.','Project into multiple QKV sets.','Heads attend in parallel.','Merge head outputs.','Feed the combined signal onward.'],
      'Translation alignments','Different heads may track different alignment patterns.','Parallel perspectives enrich representations.',
      [q('Multi-head means…',['Many computers under a desk','Parallel attention subspaces','Many CSS files','Multiple passwords'],1,'Parallel heads.'),q('Heads are always human-interpretable.',['True','False','Only Fridays','Only in JSON'],1,'Specialization is emergent, not guaranteed.'),q('Outputs of heads are typically…',['Deleted','Concatenated and projected','Converted to MP3','Emailed'],1,'Merge then continue.')],
      toggle(['1 head only','8 heads','512 heads on a tiny model'],{'1 head only':'Less diverse relational capacity.','8 heads':'Common practical setting.','512 heads on a tiny model':'Diminishing returns risk.'})),
    c('feed-forward-network','Feed-Forward Network','Per-token MLP that refines representations','intermediate',7,['multi-head-attention'],
      'After attention mixes information across tokens, a position-wise feed-forward network transforms each token vector independently. Intuitively, attention is communication; the FFN is private computation.',
      'Group discussion (attention) then each person quietly rewrites their notes (FFN).',
      ['FFN applies the same MLP at each position.','Usually expand, nonlinearity, project back.','Pairs with attention inside each block.','Holds substantial parameter count in LLMs.'],
      [['FFN / MLP','Position-wise feed-forward layers'],['GeLU/ReLU','Common nonlinearities'],['Block','Attention plus FFN unit with residuals/norms']],
      ['Contextual vectors leave attention.','Each position enters the MLP.','Hidden width expands.','Nonlinear transform applied.','Projected vectors continue.'],
      'Factual association research','Studies suggest FFNs play a large role in storing associations.','Attention routes; FFNs often compute and store.',
      [q('FFN operates…',['Across users private emails by default','Position-wise on each token vector','Only without math','On CSS selectors'],1,'Per position.'),q('Attention vs FFN intuition…',['Attention mixes across tokens; FFN transforms each','FFN replaces tokenization','Neither uses numbers','Both are databases'],0,'Communicate vs compute.'),q('FFNs usually…',['Shrink then disappear','Expand then project back','Ban softmax','Delete residuals'],1,'Expand-contract pattern.')],
      toggle(['Remove FFN','Remove attention','Keep both'],{'Remove FFN':'Loses heavy per-token computation.','Remove attention':'Tokens cannot share context well.','Keep both':'Standard transformer block.'})),
    c('residual-connections','Residual Connections','Add the input back to ease deep training','intermediate',6,['feed-forward-network'],
      'Residual connections add a block input to its output so layers learn residual updates rather than whole transformations from scratch. This stabilizes deep stacks and improves gradient flow.',
      'Editing with track changes: keep the original and add a delta instead of rewriting the whole essay each time.',
      ['Output is roughly input plus layer(input).','Helps train very deep nets.','Used around attention and FFN sublayers.','Works with normalization for stability.'],
      [['Residual','Skip connection adding input to output'],['Gradient flow','How error signals propagate backward'],['Sublayer','Attention or FFN unit inside a block']],
      ['Token vector enters a sublayer.','Sublayer computes an update.','Add update to original.','Normalized result proceeds.','Deep stacks remain trainable.'],
      'Deeper models, fewer crashes','Residuals were key to training very deep nets.','Architecture details unlock depth.',
      [q('Residuals add…',['Random noise always','Input back to sublayer output','Extra taxes','CSS margins'],1,'x + F(x).'),q('They help mainly by…',['Improving gradient flow','Deleting data','Removing GPUs','Banning batching'],0,'Depth becomes trainable.'),q('Transformers use residuals…',['Never','Around major sublayers','Only in CSS','Only offline'],1,'Standard pattern.')],
      toggle(['Plain stack no skips','Residual stack','Zero the input path'],{'Plain stack no skips':'Harder to train deep.','Residual stack':'Standard stable approach.','Zero the input path':'Breaks the skip benefit.'})),
    c('layer-normalization','Layer Normalization','Stabilize activations across features','intermediate',6,['residual-connections'],
      'Layer normalization rescales activations across features for each token so values stay well-behaved through deep stacks. Combined with residuals, it stabilizes training. Placement (pre-norm vs post-norm) varies by architecture.',
      'Auto-adjusting microphone gain so each singer sits in a healthy volume range before the next effect pedal.',
      ['Normalize mean and variance across features.','Learned scale and bias restore flexibility.','Pre-norm is common in modern LLMs.','Stabilizes deep residual pipelines.'],
      [['LayerNorm','Per-token feature normalization'],['Pre-norm','Normalize before sublayer'],['Activation scale','Magnitude of neuron outputs']],
      ['Vector enters with uneven magnitudes.','Compute mean and variance.','Normalize.','Apply learned scale and bias.','Sublayer receives stable inputs.'],
      'Training deep chat models','Norm choices affect convergence speed and stability.','Small engineering choices, large training impact.',
      [q('LayerNorm mainly…',['Deletes tokens','Stabilizes feature scales','Paints icons','Sets DNS'],1,'Stabilization.'),q('Pre-norm means…',['Norm after optimizer','Normalize before the sublayer','No residuals','No attention'],1,'Placement variant.'),q('Norm works with residuals to…',['Make depth trainable','Remove datasets','Ban GPUs','Replace loss'],0,'Stability pair.')],
      toggle(['No normalization','LayerNorm','BatchNorm style only'],{'No normalization':'Training can become brittle.','LayerNorm':'Standard in transformers.','BatchNorm style only':'Less common for variable-length NLP.'})),
    c('encoder-decoder-types','Encoder/Decoder types','BERT-like, GPT-like, and seq2seq layouts','intermediate',8,['layer-normalization'],
      'Transformer families differ by attention layout. Encoder-only models bidirectional-encode inputs. Decoder-only models causally generate left-to-right. Encoder-decoder models encode a source then decode a target.',
      'Encoder is reading comprehension; decoder is writing with only past drafts visible; encoder-decoder is read then write.',
      ['Encoder: bidirectional context.','Decoder: causal mask for generation.','Encoder-decoder: conditional generation.','Choose by task: understand, generate, or transform.'],
      [['Causal mask','Block attending to future tokens'],['Bidirectional','See left and right context'],['Seq2seq','Map an input sequence to an output sequence']],
      ['Task appears: classify, chat, or translate.','Pick architecture family.','Wire attention masks accordingly.','Train objective matches layout.','Deploy the right interface.'],
      'T5-style unification','Many NLP tasks cast as text-to-text with encoder-decoder models.','Layout follows the information flow you need.',
      [q('Chat GPTs are typically…',['Encoder-only','Decoder-only','Spreadsheets','Routers'],1,'Causal decoders.'),q('BERT-like models are…',['Encoder-oriented','Only diffusion','Only audio','Only CSS'],0,'Bidirectional encoders.'),q('Translation classic fit…',['Encoder-decoder','No neural nets','Only regex','Only FTP'],0,'Seq2seq.')],
      toggle(['Spam classify','Write a story','Translate docs'],{'Spam classify':'Encoder/classifier style.','Write a story':'Decoder-only generation.','Translate docs':'Encoder-decoder strong classic.'})),
    c('autoregressive-decoding','Autoregressive Decoding','Generate the next token using past tokens only','intermediate',7,['encoder-decoder-types'],
      'Autoregressive decoding produces tokens one by one, each conditioned on previously generated tokens and the prompt. That is why chat models stream words and why early mistakes can cascade.',
      'Writing a sentence aloud without erasing: each new word must fit what you already said.',
      ['Predict token t given tokens before t.','Append sample and repeat.','Streaming UX matches this loop.','Errors compound; decoding strategy matters.'],
      [['Autoregressive','Left-to-right sequential generation'],['Prefix','Tokens already fixed'],['Stop condition','EOS token or max length']],
      ['Prompt tokens fixed.','Model predicts next distribution.','Sample or argmax a token.','Append to prefix.','Repeat until stop.'],
      'Live token streaming','UIs show partial answers as tokens arrive.','AR decoding enables incremental UX.',
      [q('Autoregressive models generate…',['All tokens independently at once always','Sequentially conditioned on the past','Only images','Only hashes'],1,'Sequential conditioning.'),q('An early wrong token can…',['Never matter','Steer later tokens off course','Speed up light','Fix DNS'],1,'Error cascade.'),q('Streaming is natural because…',['Tokens arrive one after another','Browsers forbid text','GPUs hate math','CSS forbids words'],0,'Sequential emission.')],
      toggle(['Greedy top token','Sample with temperature','Beam search for short outputs'],{'Greedy top token':'Deterministic but can be dull.','Sample with temperature':'More variety; needs tuning.','Beam search for short outputs':'Classic for some structured tasks.'})),
    c('next-token-prediction','Next-Token Prediction','The core training and inference objective','beginner',8,['autoregressive-decoding'],
      'Next-token prediction asks: given previous tokens, what is the probability distribution over the next token? Pretraining minimizes error on this task at scale; inference samples from it. Rich behaviors emerge without guaranteeing truth.',
      'A fill-in-the-next-word game played billions of times until the player becomes an expert stylist of continuations.',
      ['Loss compares predicted distribution vs actual next token.','Inference samples from the distribution.','Capabilities emerge from objective plus data.','Calibration and factuality still need extra systems.'],
      [['Logits','Raw scores before softmax'],['Softmax','Convert scores to probabilities'],['Teacher forcing','Train on true prefixes']],
      ['Prefix: The cat sat on the.','Model outputs scores for many tokens.','Softmax yields probabilities.','mat ranks high.','Sample and continue.'],
      'Email subject autocomplete','Productive continuation without understanding your whole company.','Prediction is not verified knowledge.',
      [q('The core LLM objective is…',['Next-token prediction','Sorting arrays','Compiling C','Rendering CSS'],0,'NTP.'),q('Softmax turns logits into…',['Files','Probabilities','Pods','Fonts'],1,'Distributions.'),q('Fluent next tokens imply true facts.',['Always','Not necessarily','Never useful','Only in Latin'],1,'Fluency is not truth.')],
      ['decode-sampler']),
    c('temperature-top-k-top-p','Temperature / Top-k / Top-p','Knobs that shape randomness of sampling','intermediate',9,['next-token-prediction'],
      'Decoding strategies reshape the next-token distribution. Temperature softens or sharpens probabilities. Top-k keeps only k highest tokens; top-p keeps the smallest set whose cumulative probability exceeds p. These knobs trade creativity versus stability.',
      'Temperature is spice level; top-k and top-p cut off absurd ingredients.',
      ['Temperature divides logits before softmax.','Low temp is peaky; high temp is flatter.','Top-k and top-p truncate the tail.','Task-dependent tuning beats dogma.'],
      [['Temperature','Softmax sharpness control'],['Top-k','Keep k best tokens'],['Top-p / nucleus','Keep probability mass at least p']],
      ['Model yields raw logits.','Apply temperature scaling.','Optionally mask with top-k or top-p.','Softmax on reduced set.','Sample the next token.'],
      'Creative copy vs legal boilerplate','Marketing wants higher temperature; contracts want near-greedy decoding.','Match sampler to risk tolerance.',
      [q('Higher temperature generally…',['Always increases factuality','Flattens distribution toward more randomness','Deletes context','Removes GPUs'],1,'More random.'),q('Top-p sampling keeps…',['All tokens always','A dynamic nucleus of probability mass','Only verbs','Only digits'],1,'Nucleus.'),q('For strict formatting, prefer…',['Maximum chaos','Lower temperature or constrained decoding','Infinite temperature','No evaluation'],1,'Stability first.')],
      ['temperature']),
    c('text-generation-loop','Text Generation Loop','The full prompt to sample to append cycle','beginner',7,['temperature-top-k-top-p'],
      'The generation loop tokenizes the prompt, repeatedly samples a next token under the decoding policy, appends it, and stops on end-of-sequence, max length, or a stop string. Tool-using apps insert actions inside or around this loop.',
      'A typewriter that guesses the next character, types it, then guesses again until it stops.',
      ['Encode prompt.','Decode step-by-step.','Apply stop rules.','Detokenize to text.','Optionally stream partial results.'],
      [['EOS','End-of-sequence token'],['Max tokens','Hard length cap'],['Stop sequence','String that halts generation']],
      ['Receive prompt.','Tokenize.','Sample next token.','Append and check stops.','Detokenize and return.'],
      'Chat UX streaming','Tokens appear as the loop runs for perceived speed.','Loop mechanics shape product feel.',
      [q('Generation stops when…',['EOS, max, or stop hit','The sun explodes only','CSS loads','DNS fails'],0,'Stop conditions.'),q('Appending tokens updates…',['The prefix for the next prediction','Only the footer CSS','Kubernetes','The BIOS'],0,'AR state.'),q('Detokenization converts…',['IDs back to text','Text to electricity','Pods to fonts','JSON to rain'],0,'Readable output.')],
      toggle(['Stop on EOS','Stop on code fence','Hit max tokens mid-sentence'],{'Stop on EOS':'Natural completion.','Stop on code fence':'Useful for code block control.','Hit max tokens mid-sentence':'Truncation artifact.'})),
    c('why-hallucinations-happen','Why Hallucinations Happen','Fluent guesses without grounded truth checks','beginner',8,['text-generation-loop'],
      'Hallucinations happen because models optimize for plausible continuations, not verified world state. When context is missing or conflicting, the model still produces confident-sounding text. Decoding randomness, outdated data, and prompts that forbid uncertainty amplify the issue.',
      'A skilled improv actor who never says I do not know unless trained to—and invents details to keep the scene going.',
      ['Objective is plausible tokens, not database lookup.','Gaps get filled with likely-sounding content.','Prompts can demand answers without uncertainty.','Mitigations include retrieval, tools, citations, refusals, and evals.'],
      [['Hallucination','Confident false or unverifiable content'],['Grounding','Tying answers to sources or tools'],['Calibration','Matching confidence to correctness']],
      ['Hard question, weak evidence.','Model still must emit tokens.','Prior patterns suggest a tidy answer.','Fluent falsehood appears.','Grounding systems could interrupt.'],
      'Fake case citations','Legal tools invented case law that looked real.','High-stakes domains need grounding and verification.',
      [q('Hallucinations stem largely from…',['Optimizing plausible text without guaranteed grounding','Evil GPUs','CSS bugs','USB-C'],0,'Plausibility objective.'),q('A useful mitigation is…',['Never evaluate','RAG, tools, and verification','Delete logs','Raise temperature always'],1,'Ground and check.'),q('Fluency guarantees truth.',['Yes','No','Only in poetry','Only offline'],1,'No.')],
      toggle(['Answer with sources only','Force an answer with no context','Allow I am not sure'],{'Answer with sources only':'Reduces unsupported claims.','Force an answer with no context':'Hallucination bait.','Allow I am not sure':'Healthy uncertainty.'})),
  ],
};

// Continue in part 2 file import
const part2 = await import('./seeds-part2.mjs');
const part3 = await import('./seeds-part3.mjs');
Object.assign(seeds, part2.seeds, part3.seeds);

fs.writeFileSync(path.join(__dirname, 'concept-seeds.json'), JSON.stringify(seeds, null, 2));
const counts = Object.fromEntries(Object.entries(seeds).map(([k, v]) => [k, v.length]));
console.log(counts);
console.log('total', Object.values(seeds).reduce((a, b) => a + b.length, 0));
