const q = (prompt, options, correct, explanation) => [prompt, options, correct, explanation];
const toggle = (options, insights) => ['toggle', options, insights];
function c(...args) {
  return args.filter((x) => x !== undefined);
}

export const seeds = {
  'training-alignment': [
    c('datasets','Datasets','The raw fuel of model behavior','beginner',7,[],
      'Datasets are collections of examples used to train or evaluate models. For LLMs this may be web text, books, code, instructions, or preference pairs. Data quality, licensing, diversity, and filters shape capabilities and harms more than most people expect.',
      'You are what you eat—models absorb the statistics of their data diet.',
      ['Pretraining corpora are huge and noisy.','Fine-tune sets are smaller and task-focused.','Eval sets must not leak into training.','Governance covers consent, license, PII, and bias.'],
      [['Corpus','Large text collection'],['Label','Desired output annotation'],['Data leakage','Train/test contamination']],
      ['Collect raw sources.','Filter and deduplicate.','Split train/validation/test.','Document provenance.','Train and evaluate carefully.'],
      'Code models','Training on repositories boosts coding help—and can memorize secrets if unfiltered.','Data policy is model policy.',
      [q('Datasets primarily…',['Decorate UIs','Provide learning signal examples','Replace loss functions','Cool GPUs'],1,'Fuel for learning.'),q('Eval data should…',['Always equal training data','Stay separate to measure generalization','Be deleted always','Be only emojis'],1,'No leakage.'),q('Licensing matters because…',['Fonts look nicer','Legal and ethical constraints bind training data','GPUs hate licenses','CSS requires it'],1,'Compliance and ethics.')],
      toggle(['Web crawl dump','Curated textbooks and code','Personal emails without consent'],{'Web crawl dump':'Scale plus noise plus legal risk.','Curated textbooks and code':'Higher signal, smaller scale.','Personal emails without consent':'Hard no—privacy violation.'})),
    c('preprocessing','Preprocessing','Clean and shape raw data before training','beginner',6,['datasets'],
      'Preprocessing turns messy raw sources into trainable examples: cleaning, filtering toxicity and PII, language detection, deduplication, formatting dialogues, and packing sequences. Bad preprocessing silently poisons quality.',
      'Washing and measuring ingredients before cooking—the model only tastes what you prep.',
      ['Normalize encodings and formats.','Filter harmful or private content.','Deduplicate near-copies.','Structure into tensors and batches.'],
      [['Deduplication','Removing repeated near-identical samples'],['PII','Personally identifiable information'],['Packing','Combining short examples into sequences']],
      ['Raw messy text.','Strip boilerplate.','Filter PII and abuse.','Deduplicate.','Emit clean training records.'],
      'Chat instruction formatting','Messages labeled system/user/assistant become supervised samples.','Structure teaches roles.',
      [q('Preprocessing happens…',['After the universe ends','During dataset prep for training','Only in CSS','Only on phones'],1,'Data prep stage.'),q('Deduplication helps…',['Memorize more spam','Reduce repetitive bias from clones','Delete GPUs','Ban Unicode'],1,'Less clone dominance.'),q('PII filtering aims to…',['Increase secrets in models','Reduce private data memorization risk','Remove math','Break tokenizers'],1,'Privacy hygiene.')],
      toggle(['Keep all duplicates','Aggressive dedupe','Strip PII patterns'],{'Keep all duplicates':'Wastes compute.','Aggressive dedupe':'Often improves quality.','Strip PII patterns':'Necessary privacy step.'})),
    c('tokenization-training','Tokenization (training view)','Choose a vocab that shapes learning','intermediate',7,['preprocessing'],
      'From a training view, tokenization is a compression and inductive-bias choice: vocabulary size and special tokens affect sequence lengths, rare word handling, multilingual fairness, and throughput.',
      'Deciding whether your kitchen cuts veggies into cubes or ribbons—same ingredients, different cooking dynamics.',
      ['Fit tokenizer on domain-relevant text.','Special tokens mark roles and boundaries.','Domain mismatch hurts efficiency.','Frozen tokenizers couple to embedding matrices.'],
      [['BPE','Byte Pair Encoding merges'],['Special token','Reserved symbol like EOS'],['Vocab size','Number of distinct tokens']],
      ['Sample training text.','Count and merge subwords.','Freeze vocab.','Encode corpus to IDs.','Train embeddings on those IDs.'],
      'Multilingual fairness','Tiny English-heavy vocab can over-fragment other languages.','Tokenization can encode inequity.',
      [q('Tokenizer choice affects…',['Only wallpaper color','Sequence length and learning dynamics','Ocean salinity','Mouse DPI'],1,'Core training factor.'),q('Special tokens are used to…',['Mark structure and control','Replace GPUs','Paint SVGs','Route packets'],0,'Control markers.'),q('Domain-mismatched tokenizers often…',['Help always','Over-fragment domain text','Delete loss','Ban batching'],1,'Inefficient splits.')],
      toggle(['General web vocab','Code-heavy vocab','Tiny 500-token vocab'],{'General web vocab':'Broad coverage.','Code-heavy vocab':'Better for repos.','Tiny 500-token vocab':'Long sequences, slow learning.'})),
    c('loss-function','Loss Function','The training score to minimize','beginner',7,['tokenization-training'],
      'A loss function measures how wrong predictions are. For LLMs, cross-entropy versus the true next token is standard. Training iteratively reduces loss—it does not directly maximize truth or safety.',
      'A coach scorecard: mistakes add penalty points; practice aims to lower the score.',
      ['Loss quantifies error for gradient updates.','Cross-entropy fits next-token prediction.','Low loss is a proxy, not a virtue metric.','Auxiliary losses can add constraints.'],
      [['Cross-entropy','Penalty for low probability on the true token'],['Objective','What optimization targets'],['Metric','Evaluation measure that may differ from loss']],
      ['Model predicts a distribution.','Compare to true next token.','Compute cross-entropy.','Backprop gradients.','Optimizer steps parameters.'],
      'Overconfident wrong answers','Loss can look fine on frequent patterns while rare facts stay wrong.','Monitor task metrics beyond loss.',
      [q('LLM pretraining loss is usually…',['Cross-entropy on next tokens','JPEG size','CSS lint','Ping time'],0,'CE NTP.'),q('Lower loss always means ethical behavior.',['True','False','Only Sundays','Only in Rust'],1,'Proxy is not values.'),q('Loss drives…',['Gradient updates','Only UI themes','DNS TTLs','Fan noise only'],0,'Training signal.')],
      toggle(['Track loss only','Track loss and task accuracy','Track nothing'],{'Track loss only':'Incomplete picture.','Track loss and task accuracy':'Healthier.','Track nothing':'Flying blind.'}),
      ['pseudo','Cross-entropy idea','loss = -log p(true_token | prefix)','Minimize average loss over tokens.']),
    c('gradient-descent','Gradient Descent','Nudge parameters downhill on the loss surface','beginner',8,['loss-function'],
      'Gradient descent updates parameters in the direction that locally decreases loss. The gradient indicates downhill; learning rate controls step size. Deep learning uses stochastic mini-batch estimates.',
      'Hiking down a foggy mountain: feel the slope, take a step, repeat—avoid leaping into a ravine with a huge learning rate.',
      ['Compute gradient of loss versus parameters.','Step opposite the gradient.','Learning rate is critical.','Stochastic estimates come from batches.'],
      [['Gradient','Local slope of loss'],['Learning rate','Step size'],['Local minimum','Bowl the optimizer may settle in']],
      ['Parameters at a point.','Estimate gradient from a batch.','Step downhill.','Loss trends down overall.','Repeat for many steps.'],
      'Training curves','Smooth descending loss suggests healthy LR; explosions suggest trouble.','Plots diagnose optimization.',
      [q('Gradient descent updates…',['Parameters to reduce loss','Only CSS','DNS records','Cable colors'],0,'Optimize params.'),q('Too high learning rate can…',['Diverge training','Guarantee perfection','Delete tokens safely','Fix hallucinations'],0,'Instability.'),q('SGD uses…',['Mini-batch gradient estimates','Astrology','One batch of all Earth data always','HTML comments'],0,'Stochastic batches.')],
      toggle(['Tiny LR','Sane LR','Huge LR'],{'Tiny LR':'Slow progress.','Sane LR':'Stable learning.','Huge LR':'Divergence risk.'})),
    c('backpropagation','Backpropagation','Efficiently compute gradients through the net','intermediate',8,['gradient-descent'],
      'Backpropagation applies the chain rule to compute how each parameter affected the loss, reusing intermediate calculations. Forward pass computes predictions; backward pass propagates error signals.',
      'Tracing a cooking fail backward: salty soup, who added salt, which step, adjust that step next time.',
      ['Forward computes outputs and loss.','Backward applies the chain rule.','Each weight gets a gradient.','Vanishing and exploding gradients challenged depth historically.'],
      [['Autograd','Automatic differentiation'],['Chain rule','Compose derivatives through layers'],['Backward pass','Gradient propagation phase']],
      ['Forward through layers.','Arrive at loss.','Send gradients backward.','Each weight receives a gradient.','Optimizer applies updates.'],
      'Framework training','PyTorch and JAX compute grads via autograd graphs.','You design the graph; backprop fills gradients.',
      [q('Backprop computes…',['Gradients via chain rule','New GPUs','CSS grids','SSL certs'],0,'Gradients.'),q('Forward pass…',['Computes predictions and loss','Deletes weights','Only shuffles tokens','Paints UI'],0,'Outputs.'),q('Autograd means…',['Manual quill math always','Automatic differentiation of the compute graph','No training','No batches'],1,'Auto diffs.')],
      toggle(['Manual derivatives for a 7B model','Autograd','Ignore gradients'],{'Manual derivatives for a 7B model':'Impractical.','Autograd':'Standard.','Ignore gradients':'No learning.'})),
    c('optimizers','Optimizers','Algorithms that apply gradients wisely','intermediate',7,['backpropagation'],
      'Optimizers decide how to turn gradients into parameter updates. SGD, Momentum, Adam, and AdamW add adaptive step sizes and regularization behaviors that affect speed, stability, and final quality.',
      'Not just walk downhill, but whether you use hiking poles or adapt stride to terrain.',
      ['SGD is simple and sometimes sharp.','Momentum smooths updates.','Adam and AdamW adapt per-parameter rates.','Weight decay curbs parameter growth.'],
      [['AdamW','Adaptive optimizer with decoupled weight decay'],['Momentum','Velocity carrying past gradients'],['Weight decay','Parameter magnitude penalty']],
      ['Receive gradients.','Optimizer adapts the step.','Apply to weights.','Track moving stats if adaptive.','Repeat next batch.'],
      'Stable pretraining runs','Optimizer and schedule tweaks prevent costly divergences.','Optimization is part of the research.',
      [q('Optimizers convert gradients into…',['Parameter updates','Podcasts','Dockerfiles','Font files'],0,'Updates.'),q('AdamW is popular because…',['It bans data','Adaptive steps and weight decay work well','It removes loss','It paints icons'],1,'Practical stability.'),q('Weight decay tends to…',['Encourage huge weights','Penalize large weights','Delete softmax','Stop tokenization'],1,'Regularize magnitude.')],
      toggle(['Plain SGD no schedule','AdamW with LR schedule','Random weight jerks'],{'Plain SGD no schedule':'Can work; may be slow.','AdamW with LR schedule':'Common modern default.','Random weight jerks':'Not an optimizer.'})),
    c('epochs-batches-lr','Epochs / Batches / LR','The rhythm of training steps','beginner',7,['optimizers'],
      'Data is processed in batches. An epoch is one pass over the training set. Learning rate schedules change step size over time. For LLMs, tokens seen often matters more than epoch count.',
      'Gym plan: sets are batches, full routines are epochs, and weekly weight is the LR schedule.',
      ['Batch size trades noise versus compute.','Epochs measure progress through data.','LR schedules prevent early shocks.','Token budgets dominate LLM training talk.'],
      [['Batch','Group of examples per update'],['Epoch','Pass through dataset'],['LR schedule','Plan for learning rate over time']],
      ['Shuffle data.','Take a batch.','Update with current LR.','Advance schedule.','Complete epoch or token budget.'],
      'Warmup saves runs','Too-high early LR destabilizes; warmup ramps gently.','Schedules are practical engineering.',
      [q('A batch is…',['One GPU brand','A group of examples per step','A CSS file','A DNS zone'],1,'Step group.'),q('Warmup means…',['Gradually increase LR early','Delete data','Ban Adam','Stop evals'],0,'Gentle start.'),q('For LLMs people often track…',['Tokens processed','Only wallpaper','Only fan RPM','Only commit emojis'],0,'Token budgets.')],
      toggle(['Batch size 1','Moderate batches','Enormous batch with tiny LR'],{'Batch size 1':'Noisy and slow.','Moderate batches':'Common balance.','Enormous batch with tiny LR':'Possible with care.'})),
    c('pretraining-vs-finetuning','Pretraining vs Fine-tuning','Broad learning first, specialize second','beginner',7,['epochs-batches-lr'],
      'Pretraining teaches general patterns from massive data. Fine-tuning continues training on narrower data to specialize behavior. Most products adapt a pretrained base because pretraining is extremely expensive.',
      'Learn general literacy first, then take a professional short course.',
      ['Pretrain is expensive and broad.','Fine-tune is cheaper adaptation.','Catastrophic forgetting is a risk.','Parameter-efficient methods often beat full fine-tunes.'],
      [['Pretraining','Large-scale general training'],['Fine-tuning','Task or domain adaptation'],['Catastrophic forgetting','Losing old skills while learning new']],
      ['Pretrain on broad corpora.','Obtain a base model.','Fine-tune on domain data.','Evaluate general and domain metrics.','Ship adaptation with safeguards.'],
      'Hospital note summarizer','Start from a general LLM; fine-tune on de-identified note styles.','Do not pretrain from scratch for every app.',
      [q('Pretraining is usually…',['Narrow and tiny','Broad and expensive','Only CSS','Only mobile'],1,'Scale stage.'),q('Fine-tuning…',['Adapts a base model','Deletes the base always','Replaces electricity','Bans prompts'],0,'Specialize.'),q('Forgetting risk means…',['New training can erode old skills','GPUs forget math','Tokens vanish from Unicode','Logs delete themselves'],0,'Catastrophic forgetting.')],
      toggle(['Train from scratch for FAQ bot','Fine-tune base','Prompt only'],{'Train from scratch for FAQ bot':'Usually wasteful.','Fine-tune base':'Strong when domain data exists.','Prompt only':'Cheapest starting point.'})),
    c('sft','SFT','Supervised Fine-Tuning on instructions','intermediate',7,['pretraining-vs-finetuning'],
      'Supervised Fine-Tuning trains the model on high-quality prompt-response examples so it follows instructions in a desired style. It turns a base completion model into a more helpful assistant before preference optimization.',
      'Script rehearsal: show ideal dialogues until the actor hits the right tone and structure.',
      ['Curate instruction datasets.','Minimize loss on target responses.','Quality beats sheer quantity.','SFT alone may still hallucinate.'],
      [['Instruction tuning','Fine-tuning to follow instructions'],['Gold response','Target answer text'],['Demonstration data','Example dialogues']],
      ['Base model completes text.','Provide instruction examples.','SFT updates toward gold answers.','Assistant-style behavior emerges.','Later preference stages refine choices.'],
      'Company tone of voice','SFT on approved templates yields on-brand support drafts.','Demonstrations teach manners and format.',
      [q('SFT stands for…',['Supervised Fine-Tuning','Super Fast TCP','Soft Font Type','Secure File Telegram'],0,'SFT.'),q('SFT uses…',['Labeled prompt-response pairs','Only unlabeled noise','Only rewards without text','Only CSS'],0,'Supervised pairs.'),q('Quality of demos…',['Barely matters','Strongly drives behavior','Deletes GPUs','Fixes networking'],1,'Quality over quantity.')],
      toggle(['Noisy scraped Q&A','Expert-reviewed demos','Contradictory instructions'],{'Noisy scraped Q&A':'Teaches messy habits.','Expert-reviewed demos':'Best SFT fuel.','Contradictory instructions':'Confuses behavior.'})),
    c('lora-qlora','LoRA / QLoRA','Fine-tune small adapters instead of all weights','intermediate',8,['sft'],
      'LoRA freezes most base weights and trains tiny low-rank adapter matrices, cutting memory and storage. QLoRA quantizes the base model while training adapters, enabling fine-tuning on smaller GPUs.',
      'Instead of rewriting an entire textbook, stick removable sticky notes you can swap per subject.',
      ['Inject low-rank updates into layers.','Train adapters; freeze base.','QLoRA uses a quantized base plus adapters.','Swap adapters per task or tenant.'],
      [['LoRA','Low-Rank Adaptation'],['Quantization','Store weights with fewer bits'],['Adapter','Small trainable module']],
      ['Load base model.','Insert LoRA adapters.','Optionally quantize base.','Train adapters on task data.','Ship tiny adapter files.'],
      'Multi-tenant customization','One base plus many per-customer adapters.','Efficient specialization at scale.',
      [q('LoRA trains…',['Small adapter matrices typically','Every marketing PDF','Only CSS variables','DNS records'],0,'Adapters.'),q('QLoRA helps by…',['Quantizing base to save memory','Deleting attention','Banning data','Removing loss'],0,'Memory efficiency.'),q('Adapters are useful because…',['They are swappable and small','They erase bases always','They forbid evals','They replace tokenizers'],0,'Modularity.')],
      toggle(['Full fine-tune 70B on one laptop','LoRA','QLoRA on limited VRAM'],{'Full fine-tune 70B on one laptop':'Usually impossible.','LoRA':'Efficient adaptation.','QLoRA on limited VRAM':'Practical on smaller GPUs.'}),
      ['pseudo','LoRA idea',"W' = W + BA  (B,A low-rank trained)",'Base W frozen.']),
    c('rlhf','RLHF','Align with human preferences via rewards','advanced',9,['lora-qlora'],
      'Reinforcement Learning from Human Feedback fits a reward model on human preference comparisons, then optimizes the LLM policy to score higher while staying close to a reference model. It can improve helpfulness but is complex and can over-optimize quirks.',
      'A comedy writer tries jokes, audience ranks them, coach trains for crowd-pleasers without wandering off-character.',
      ['Collect pairwise human preferences.','Train a reward model.','Optimize policy with RL plus KL penalty.','Expensive and sensitive to preference data.'],
      [['Reward model','Model predicting preference scores'],['Policy','The generating LLM being optimized'],['KL penalty','Keep policy near reference']],
      ['Humans compare answers.','Reward model learns preferences.','Policy samples answers.','Update toward higher reward.','Stay near reference behavior.'],
      'Assistant helpfulness jumps','Chat models became more instruction-following after preference tuning eras.','Human preferences shape product feel.',
      [q('RLHF uses…',['Preference feedback to shape rewards','Only unsupervised clustering','Only CSS','Only ping'],0,'Preferences.'),q('KL penalties aim to…',['Prevent drifting too far from reference','Delete tokens','Ban GPUs','Stop tokenization'],0,'Stay close.'),q('RLHF is…',['Simple regex','Complex but influential alignment method','A font','A cable'],1,'Powerful and heavy.')],
      toggle(['No preference stage','RLHF','Only SFT'],{'No preference stage':'More raw completion behavior.','RLHF':'Preference-optimized.','Only SFT':'Strong baseline before RL.'})),
    c('dpo','DPO','Preference tuning without a full RL loop','advanced',8,['rlhf'],
      'Direct Preference Optimization fine-tunes on preferred versus rejected responses using a classification-style objective that avoids a separate RL loop. It is often simpler operationally than classic RLHF.',
      'Show good versus bad answers and teach prefer this over that, without a separate scoreboard coach in an RL loop.',
      ['Dataset holds prompt, chosen, rejected.','Optimize a closed-form preference loss.','No explicit reward-model RL loop required.','Still depends on preference data quality.'],
      [['Chosen','Preferred response'],['Rejected','Dispreferred response'],['Reference model','Anchor for implicit regularization']],
      ['Gather preference triples.','Compute DPO loss.','Update policy parameters.','Preferred style becomes likelier.','Evaluate regressions.'],
      'Safer refusal style','Teams use DPO to nudge refusals without heavy RL ops.','Operational simplicity matters.',
      [q('DPO trains on…',['Chosen versus rejected responses','Only unlabeled audio','Only CSS','Only IP addresses'],0,'Preference pairs.'),q('DPO typically avoids…',['A full RL loop with explicit reward model','Any math','Any data','Any eval'],0,'Simpler pipeline.'),q('Bad preference data yields…',['Magic safety','Misaligned behavior','Free GPUs','Perfect truth'],1,'Garbage in, garbage out.')],
      toggle(['RLHF stack','DPO','No preference optimization'],{'RLHF stack':'Powerful, ops-heavy.','DPO':'Simpler preference tuning.','No preference optimization':'Misses preference shaping.'}),
      ['pseudo','DPO sketch','increase log π(chosen) relative to π(rejected)\n(with reference constraints)','See the DPO paper for details.']),
    c('overfit-underfit','Overfit / Underfit intuition','Memorize too hard versus learn too little','beginner',7,['dpo'],
      'Underfitting means the model is too simple or under-trained. Overfitting means it memorizes training quirks and fails to generalize. Watch train versus validation metrics for gaps.',
      'Underfit: studying only chapter titles. Overfit: memorizing answer keys, then freezing on a new question.',
      ['Train and val curves diagnose fit.','Regularization and more data fight overfit.','More capacity or training can fix underfit.','LLMs can memorize; privacy and eval design matter.'],
      [['Overfitting','Great train, poor generalization'],['Underfitting','Poor train and poor generalization'],['Regularization','Techniques limiting memorization']],
      ['Train accuracy climbs.','Validation stalls or drops.','Suspect overfitting.','Add data, regularize, or stop earlier.','Generalization improves.'],
      'Leaderboard leakage','Tuning to a public test set overfits the leaderboard.','Hold out truly unseen tests.',
      [q('Overfitting looks like…',['Train up, validation down','Both always perfect forever','No training','Only CSS bugs'],0,'Gap pattern.'),q('Underfitting means…',['Model too weak or undertrained','Too much perfect memory','Infinite context','No loss'],0,'Too simple.'),q('A remedy for overfit…',['More diverse data and regularization','Delete validation','Max LR chaos always','Ignore metrics'],0,'Generalization tools.')],
      toggle(['Tiny model, huge task','Huge model, tiny duplicated set','Right-sized model and diverse data'],{'Tiny model, huge task':'Underfit risk.','Huge model, tiny duplicated set':'Overfit risk.','Right-sized model and diverse data':'Healthier fit.'})),
  ],

  'prompt-engineering': [
    c('roles-system-user-assistant','Roles (system/user/assistant)','Who is speaking in the dialogue format','beginner',6,[],
      'Chat models are trained on roles: system sets policy and persona, user provides requests, assistant responds. Clear role separation improves control. System messages are powerful but not magical security boundaries.',
      'A play script: stage directions (system), audience request (user), actor lines (assistant).',
      ['System steers global behavior.','User turns carry tasks.','Assistant turns are model outputs.','Do not treat system prompts as perfect sandboxing.'],
      [['System prompt','High-level instructions and policies'],['User message','Human or app request'],['Assistant message','Model response']],
      ['Define system policy.','User asks a question.','Assistant answers in-policy.','Next user turn continues.','Roles keep structure stable.'],
      'Support bot persona','System: be brief and cite policy; user asks refund question.','Roles encode product behavior.',
      [q('System role mainly…',['Sets policy and persona','Replaces the GPU','Is the user question','Is CSS'],0,'Global steering.'),q('Assistant role is…',['The model response channel','Always the database','Only offline','A Kubernetes node'],0,'Model output.'),q('System prompts are perfect security.',['True','False','Only on Mondays','Only in XML'],1,'Not a hard security boundary.')],
      toggle(['No system prompt','Clear system policy','Stuff secrets only in system prompt'],{'No system prompt':'Less consistent behavior.','Clear system policy':'Better steering.','Stuff secrets only in system prompt':'Unsafe assumption.'})),
    c('zero-one-few-shot','Zero / One / Few-shot','Teach by giving zero to a few examples','beginner',7,['roles-system-user-assistant'],
      'Zero-shot asks the model to perform a task with instructions only. One-shot and few-shot provide example input-output pairs in the prompt so the model mirrors the pattern. Examples are a lightweight way to specify format and style without fine-tuning.',
      'Showing a worked example on the blackboard before asking students to do the next problem.',
      ['Zero-shot: instructions alone.','Few-shot: demos in context.','Pick diverse, correct examples.','Too many demos can crowd the context window.'],
      [['Zero-shot','No examples in the prompt'],['Few-shot','Multiple in-context examples'],['In-context learning','Adapting from prompt examples']],
      ['State the task.','Optionally add examples.','Ask for the new case.','Model mirrors the pattern.','Check format adherence.'],
      'Ticket triage labels','Show three labeled tickets, then ask for the fourth label.','Examples specify the label taxonomy quickly.',
      [q('Few-shot prompting provides…',['Examples in the prompt','New GPU drivers','A database schema automatically','CSS themes'],0,'In-context demos.'),q('Zero-shot means…',['No examples, instructions only','Zero temperature always','No tokens','No model'],0,'Instructions only.'),q('Bad examples usually…',['Help always','Teach the wrong pattern','Delete context','Fix hallucinations'],1,'Demos are teachers.')],
      toggle(['Zero-shot extract JSON','One good example','Five conflicting examples'],{'Zero-shot extract JSON':'Works if instructions are crisp.','One good example':'Often stabilizes format.','Five conflicting examples':'Confuses the pattern.'})),
    c('chain-of-thought','Chain of Thought','Ask for step-by-step reasoning','intermediate',8,['zero-one-few-shot'],
      'Chain-of-Thought (CoT) prompting asks the model to reason in intermediate steps before the final answer. For multi-step problems, visible reasoning often improves accuracy—though steps can also look convincing while being wrong.',
      'Show your work on a math quiz: intermediate lines catch arithmetic slips.',
      ['Encourage stepwise reasoning.','Helps on multi-step tasks.','Does not guarantee correctness.','Can be combined with self-consistency or tools.'],
      [['Chain of Thought','Intermediate reasoning tokens'],['Final answer','The concluded result'],['Scratchpad','Working space for steps']],
      ['Pose a multi-step question.','Ask for step-by-step reasoning.','Model emits intermediate steps.','Conclude with an answer.','Verify the steps.'],
      'Physics word problems','Students prompt think step by step for unit conversions.','Process scaffolding lifts performance.',
      [q('CoT mainly asks the model to…',['Hide all reasoning','Write intermediate reasoning steps','Delete tokens','Ban math'],1,'Show work.'),q('CoT guarantees correctness.',['True','False','Only in rhyme','Only offline'],1,'Helpful but fallible.'),q('CoT helps most when…',['Tasks are multi-step','Tasks are single-token copies','CSS is involved','DNS is down'],0,'Multi-step reasoning.')],
      ['prompt-builder']),
    c('self-consistency','Self-Consistency','Sample multiple reasonings and vote','intermediate',7,['chain-of-thought'],
      'Self-consistency samples several chain-of-thought trajectories (usually with temperature) and selects the most common final answer. Agreement across diverse paths often beats one greedy reasoning trace.',
      'Ask three study partners to solve independently, then trust the answer they converge on.',
      ['Sample multiple reasoning paths.','Extract final answers.','Majority vote.','Costs more tokens.','Helps when reasoning is brittle.'],
      [['Self-consistency','Vote over multiple sampled solutions'],['Diversity','Different reasoning paths'],['Majority vote','Pick the most common answer']],
      ['Ask a hard question.','Sample N CoT answers.','Parse finals.','Vote.','Return consensus.'],
      'Math contest practice','Multiple samples reduce unlucky reasoning slips.','Compute trades for reliability.',
      [q('Self-consistency uses…',['Multiple sampled solutions and voting','A single forced lie','Only CSS','Only one token ever'],0,'Vote ensemble.'),q('It usually needs…',['Higher token cost','Zero compute','No parsing','No question'],0,'More samples cost more.'),q('It helps when…',['Single traces are brittle','The answer is a random GIF','Networking is off','Fonts are bold'],0,'Brittle reasoning.')],
      toggle(['One greedy CoT','Five sampled CoTs + vote','Hundred samples for a yes/no FAQ'],{'One greedy CoT':'Cheap, riskier.','Five sampled CoTs + vote':'Common reliability boost.','Hundred samples for a yes/no FAQ':'Overkill cost.'})),
    c('tree-of-thoughts','Tree of Thoughts','Explore branching reasoning options','advanced',8,['self-consistency'],
      'Tree of Thoughts explores multiple partial reasoning branches, evaluates them, and expands promising ones—more search-like than a single linear chain. It can improve hard planning problems at higher complexity and cost.',
      'A chess player considers several move trees, prunes weak lines, and deepens strong ones.',
      ['Propose multiple next thoughts.','Evaluate branches.','Expand the best candidates.','Prune weak paths.','Heavier than linear CoT.'],
      [['Branch','An alternative partial solution'],['Evaluation','Scoring intermediate thoughts'],['Search','Exploring a tree of options']],
      ['Root problem posed.','Generate candidate thoughts.','Score them.','Expand top branches.','Choose best leaf answer.'],
      'Puzzle solving demos','ToT-style search helps certain planning puzzles.','Search wrappers sit around the LLM.',
      [q('Tree of Thoughts is…',['Branching exploration of reasoning','A CSS layout only','A database index','A GPU brand'],0,'Branching search.'),q('Compared with linear CoT, ToT is usually…',['Cheaper always','More expensive and search-like','Impossible','Only for images'],1,'Heavier.'),q('Pruning means…',['Dropping weak branches','Deleting the model','Banning prompts','Formatting JSON'],0,'Cut weak lines.')],
      toggle(['Linear CoT','Tree search of thoughts','Random words'],{'Linear CoT':'Simple path.','Tree search of thoughts':'Explore alternatives.','Random words':'Not reasoning.'})),
    c('react-prompting','ReAct prompting','Interleave reasoning with actions','intermediate',8,['tree-of-thoughts'],
      'ReAct prompting structures outputs as interleaved Thought, Action, and Observation. The model plans, calls a tool, reads the result, and continues. It is a prompting pattern that later becomes the backbone of many agents.',
      'A lab notebook: hypothesize, run an experiment, record the observation, then decide the next step.',
      ['Think about what is needed.','Act with a tool or API.','Observe the result.','Repeat until answerable.','Reduces pure hallucination on lookup tasks.'],
      [['Thought','Internal plan text'],['Action','Tool call'],['Observation','Tool result']],
      ['User asks a grounded question.','Thought: need a lookup.','Action: call tool.','Observation returns facts.','Final answer uses observations.'],
      'Weather plus outfit advice','Thought needs weather; action calls API; observation guides clothing advice.','Tools ground the loop.',
      [q('ReAct interleaves…',['Thought, action, observation','Only CSS and HTML','Only loss and accuracy','Only pods and nodes'],0,'TAO loop.'),q('Actions are typically…',['Tool calls','Random poetry only','GPU temperatures','Font downloads'],0,'Tools.'),q('Observations are…',['Tool results fed back','Ignored always','CSS variables','DNS TXT records only'],0,'Feedback.')],
      toggle(['Answer with no tools','ReAct with a calculator','ReAct but ignore observations'],{'Answer with no tools':'May invent numbers.','ReAct with a calculator':'Grounded arithmetic.','ReAct but ignore observations':'Defeats the pattern.'})),
    c('prompt-chaining','Prompt Chaining','Break a job into staged prompts','intermediate',7,['react-prompting'],
      'Prompt chaining splits a complex task into stages where each prompt’s output feeds the next: extract, transform, verify, format. Smaller steps are easier to control, test, and cache than one mega-prompt.',
      'An assembly line: cut, assemble, paint, inspect—rather than one chaotic workshop moment.',
      ['Decompose the workflow.','Define interfaces between steps.','Validate intermediate outputs.','Parallelize independent stages.','Easier debugging than monolith prompts.'],
      [['Chain','Sequence of prompt steps'],['Intermediate artifact','Output passed downstream'],['Validator step','Checks quality before continuing']],
      ['Big task arrives.','Step 1 extracts facts.','Step 2 drafts.','Step 3 critiques.','Step 4 formats final.'],
      'RFP response drafting','Extract requirements, draft sections, compliance check, then polish.','Chains match real document workflows.',
      [q('Prompt chaining…',['Splits work into staged prompts','Merges all GPUs','Deletes context always','Bans JSON'],0,'Staged prompts.'),q('A benefit is…',['Easier testing of steps','Guaranteed truth','Free hosting','No need for evals'],0,'Debuggability.'),q('Interfaces between steps should be…',['Clear and validated','Random','Hidden forever','Only emojis'],0,'Contracts.')],
      toggle(['One mega-prompt','Extract then draft then check','Infinite chain of 200 microsteps'],{'One mega-prompt':'Hard to debug.','Extract then draft then check':'Practical chain.','Infinite chain of 200 microsteps':'Over-fragmented latency.'})),
    c('structured-outputs','Structured Outputs','Force machine-readable answers','intermediate',7,['prompt-chaining'],
      'Structured outputs ask the model to return JSON, tables, or schema-valid objects so software can parse results reliably. Schemas, constrained decoding, and validators turn prose generators into API-friendly components.',
      'Fill a form with labeled fields instead of writing a free-form essay your parser cannot read.',
      ['Provide a schema or template.','Prefer constrained decoding when available.','Validate and retry on failure.','Keep schemas minimal and explicit.'],
      [['Schema','Expected fields and types'],['Constrained decoding','Limit tokens to valid structures'],['Validation','Check output against schema']],
      ['Define JSON schema.','Prompt for schema-only output.','Model emits JSON.','Validator checks.','App consumes fields.'],
      'Invoice field extraction','Return vendor, date, total as JSON for accounting software.','Structure bridges LLMs and programs.',
      [q('Structured outputs help…',['Programs parse results reliably','GPUs overheat less by magic','DNS resolve faster','Fonts bold themselves'],0,'Machine readability.'),q('A schema defines…',['Expected fields and types','Ocean currents','Cable colors','Only temperatures'],0,'Shape contract.'),q('On invalid JSON you should…',['Validate and retry or repair','Trust it anyway','Delete the app','Raise temperature to 100'],0,'Validate.')],
      toggle(['Free prose only','JSON schema + validation','Huge ambiguous schema'],{'Free prose only':'Hard to parse.','JSON schema + validation':'Production pattern.','Huge ambiguous schema':'Brittle compliance.'}),
      ['ts','Schema sketch','type Invoice = { vendor: string; total: number }','Keep fields tight.']),
    c('role-prompting-constraints','Role prompting & constraints','Persona plus hard rules','beginner',6,['structured-outputs'],
      'Role prompting assigns a persona (tutor, reviewer, SRE) while constraints specify hard rules: length limits, banned topics, citation requirements, or tool-only claims. Constraints matter more than theatrical personas.',
      'Costume plus safety rules: the costume sets tone; the rules keep the performance legal.',
      ['Persona shapes style.','Constraints encode non-negotiables.','Prefer testable rules.','Conflicts between style and safety need priority order.'],
      [['Persona','Assumed role or style'],['Constraint','Hard requirement'],['Priority','Which rule wins on conflict']],
      ['Assign a helpful tutor persona.','Add constraints: no final exam answers verbatim.','User asks for a solution.','Model teaches with hints.','Constraints override flair.'],
      'Exam-safe tutoring','Tutor role with ban on full answer dumps.','Constraints protect academic integrity.',
      [q('Constraints should be…',['Testable rules','Only vibes','Hidden from evals','Random'],0,'Testable.'),q('Persona mainly affects…',['Tone and framing','GPU voltage','DNS TTL','Disk format'],0,'Style.'),q('If persona conflicts with safety…',['Safety should win','Persona always wins','Flip a coin','Delete both'],0,'Priorities.')],
      toggle(['Funny persona only','Funny persona + hard privacy rules','No constraints'],{'Funny persona only':'Style without guardrails.','Funny persona + hard privacy rules':'Balanced.','No constraints':'Risky drift.'})),
    c('context-engineering','Context Engineering','Design what enters the window on purpose','intermediate',8,['role-prompting-constraints'],
      'Context engineering is the discipline of selecting, compressing, ordering, and refreshing what the model sees: instructions, tools, retrieved docs, memory, and user state. Prompts are only one ingredient; the whole window is the product.',
      'Packing a backpack for a hike: bring the map and snacks that matter, leave the encyclopedias.',
      ['Choose high-value tokens.','Order matters; put critical rules where models attend reliably.','Compress history with summaries.','Retrieve just-in-time facts.','Measure context ablations.'],
      [['Context budget','Limited token capacity'],['Memory','Persisted state outside raw chat'],['Ablation','Remove pieces to test impact']],
      ['Inventory possible context sources.','Rank by relevance.','Fit into budget.','Place instructions carefully.','Generate with that curated window.'],
      'IDE coding agents','Rules files, open tabs, and retrieved chunks are curated into context.','Engineering the window beats prompt poetry alone.',
      [q('Context engineering focuses on…',['What enters the model window','Only temperature','Only CSS','Only GPU brands'],0,'Window design.'),q('A context budget is…',['Limited token capacity','Unlimited always','A finance PDF only','A font file'],0,'Capacity.'),q('Summaries help by…',['Compressing old history','Deleting the model','Banning tools','Raising loss'],0,'Compression.')],
      toggle(['Paste everything','Rank and fit top evidence','Empty context'],{'Paste everything':'Noise and truncation.','Rank and fit top evidence':'Core skill.','Empty context':'Under-specified.'})),
    c('prompt-failure-modes','Prompt failure modes','How prompts go wrong in practice','beginner',7,['context-engineering'],
      'Prompts fail through ambiguity, conflicting instructions, missing constraints, format drift, jailbreak pressure, and overlong clutter. Treat prompts like code: test, version, and monitor regressions when models change.',
      'Vague homework instructions that get five different interpretations from five students.',
      ['Ambiguity yields variance.','Conflicts create unstable behavior.','Missing evals hide breakage.','Model upgrades can invalidate prompt assumptions.'],
      [['Ambiguity','Unclear success criteria'],['Instruction conflict','Two rules that disagree'],['Prompt regression','Old prompt fails on new model']],
      ['Ship a vague prompt.','Users interpret differently.','Outputs vary wildly.','Add constraints and examples.','Variance drops; quality rises.'],
      'Promo email generator','“Make it pop” produced chaos until length, audience, and CTA were specified.','Specificity beats adjectives.',
      [q('A common failure is…',['Ambiguous success criteria','Too much electricity','CSS being blue','USB-C'],0,'Ambiguity.'),q('Prompts should be…',['Tested like code','Never changed','Hidden from product','Written only in emojis'],0,'Engineer them.'),q('Model upgrades can…',['Invalidate prompt assumptions','Never affect prompts','Delete JSON forever','Ban evaluation'],0,'Regressions happen.')],
      toggle(['Vague adjectives','Measurable constraints','Contradictory rules'],{'Vague adjectives':'High variance.','Measurable constraints':'More reliable.','Contradictory rules':'Unstable behavior.'})),
  ],
};
