const q = (prompt, options, correct, explanation) => [prompt, options, correct, explanation];
const toggle = (options, insights) => ['toggle', options, insights];
function c(...args) {
  return args.filter((x) => x !== undefined);
}

export const seeds = {
  rag: [
    c('why-rag','Why RAG','Ground answers in your documents','beginner',7,[],
      'Retrieval-Augmented Generation (RAG) fetches relevant documents at query time and conditions the model on that evidence. It reduces reliance on parametric memory for private or changing facts and makes citations possible.',
      'An open-book exam: instead of memorizing every page, look up the chapter you need, then write the answer.',
      ['LLMs have stale or missing private knowledge.','Retrieve first, then generate.','Enables citations and updates without full retraining.','Still fails if retrieval misses or context is misused.'],
      [['RAG','Retrieve then generate'],['Parametric knowledge','Facts stored in weights'],['Grounding','Basing answers on evidence']],
      ['User asks a policy question.','System retrieves relevant docs.','Docs enter the prompt.','Model answers with evidence.','Optional citations shown.'],
      'HR policy assistant','Employees ask about leave; answers come from the latest handbook chunks.','Update docs without retraining the LLM.',
      [q('RAG mainly helps by…',['Fetching evidence for generation','Deleting models','Replacing GPUs','Banning prompts'],0,'Retrieve then generate.'),q('A benefit is…',['Easier knowledge updates','Infinite perfect memory','No need for evals','Free electricity'],0,'Updatable docs.'),q('RAG guarantees no hallucinations.',['True','False','Only on Fridays','Only offline'],1,'Bad retrieval still fails.')],
      toggle(['Memorize all PDFs in weights','RAG over PDFs','Ignore documents'],{'Memorize all PDFs in weights':'Expensive and stale.','RAG over PDFs':'Practical grounding.','Ignore documents':'Invented policies risk.'})),
    c('chunking','Chunking','Split documents into retrievable pieces','beginner',7,['why-rag'],
      'Chunking splits documents into passages sized for embedding and context budgets. Too large and retrieval is noisy; too small and meaning fragments. Overlap and structure-aware splits (headings, code functions) often help.',
      'Indexing a textbook by coherent sections instead of one giant blob or single sentences with no context.',
      ['Choose chunk size for embedder and LLM.','Preserve semantic boundaries.','Overlap reduces boundary loss.','Metadata keeps source trail.'],
      [['Chunk','A retrievable text passage'],['Overlap','Shared text between adjacent chunks'],['Metadata','Source, page, section labels']],
      ['Load a document.','Split on structure.','Apply size and overlap.','Attach metadata.','Ready for embedding.'],
      'API docs RAG','Split by endpoint sections so retrieval returns whole endpoint explanations.','Structure-aware chunks win.',
      [q('Chunking is…',['Splitting docs into passages','Deleting punctuation only','GPU scheduling','CSS minify'],0,'Passages.'),q('Too-small chunks risk…',['Losing surrounding meaning','Perfect answers always','Infinite context','Free hosting'],0,'Fragmentation.'),q('Metadata helps…',['Cite and filter sources','Heat the room','Bold fonts','Route Ethernet'],0,'Provenance.')],
      toggle(['One chunk = whole book','Heading-aware medium chunks','Random 20-character shards'],{'One chunk = whole book':'Poor retrieval precision.','Heading-aware medium chunks':'Strong default.','Random 20-character shards':'Meaning destroyed.'})),
    c('embeddings-for-retrieval','Embeddings for retrieval','Encode queries and chunks into one space','intermediate',8,['chunking'],
      'Retrieval embeddings map queries and document chunks into a shared vector space so similar meanings neighbor each other. Embedding model choice, domain fit, and instruction formats strongly affect recall.',
      'Library call numbers for meaning: related books shelved near each other so you can walk to the right aisle.',
      ['Embed chunks offline.','Embed query online.','Compare vectors by similarity.','Domain mismatch hurts recall.','Re-embed when chunking changes.'],
      [['Retrieval embedding','Vector used for search'],['Recall','Did we fetch the needed evidence?'],['Domain fit','Match between embedder and corpus']],
      ['Chunk text.','Embed and store vectors.','Embed user query.','Find nearest chunk vectors.','Pass text to generator.'],
      'Bug tracker search','Semantic search finds issues describing the same crash with different words.','Meaning beats keywords alone.',
      [q('Retrieval embeddings are used to…',['Find semantically related chunks','Render CSS','Compile C','Charge phones'],0,'Semantic search.'),q('Queries and docs should be…',['In a comparable embedding space','On different planets','Unembedded','Only hashed'],0,'Shared space.'),q('Changing chunking usually means…',['Re-embedding','Never updating vectors','Deleting the LLM','Banning metadata'],0,'Keep index consistent.')],
      ['similarity']),
    c('vector-db-concept','Vector DB concept','Store and search embeddings at scale','intermediate',7,['embeddings-for-retrieval'],
      'A vector database stores embeddings plus metadata and supports nearest-neighbor search at scale. It is the index behind most RAG stacks. Think retrieval engine, not a replacement for your system of record.',
      'A specialized card catalog for coordinates of meaning, with filters for author and date.',
      ['Upsert vectors with IDs and metadata.','Query by nearest neighbors.','Filter with metadata.','ANN algorithms trade exactness for speed.','Still need the original text store.'],
      [['ANN','Approximate nearest neighbor search'],['Upsert','Insert or update a vector record'],['Metadata filter','Constrain search by fields']],
      ['Embed chunk.','Upsert into vector DB.','Query with filters.','Return top IDs.','Fetch raw text for prompting.'],
      'Enterprise knowledge base','Teams store millions of chunk vectors with ACL metadata filters.','Scale and permissions meet.',
      [q('Vector DBs specialize in…',['Nearest-neighbor embedding search','Payroll taxes','CSS grid','HDMI'],0,'Vector search.'),q('ANN means…',['Approximate nearest neighbors','Absolute never never','A new GPU','A font'],0,'Approx search.'),q('Vector DB replaces your source docs store.',['True','False','Only Sundays','Only in YAML'],1,'It indexes; source of truth remains elsewhere.')],
      toggle(['Postgres only keywords','Vector index + metadata filters','Store vectors on sticky notes'],{'Postgres only keywords':'Misses paraphrases.','Vector index + metadata filters':'RAG standard.','Store vectors on sticky notes':'Not scalable.'})),
    c('similarity-search','Similarity Search','Find nearest neighbors to a query vector','beginner',7,['vector-db-concept'],
      'Similarity search ranks stored vectors by closeness to the query embedding using metrics like cosine similarity or inner product. Top-k results become candidate passages for the LLM.',
      'Standing at a map pin and asking who is closest to me.',
      ['Embed the query.','Score against index.','Take top-k.','Optionally threshold.','Feed texts downstream.'],
      [['Top-k','Return k nearest items'],['Cosine similarity','Angle-based score'],['Candidate set','Retrieved passages before rerank']],
      ['Query arrives.','Become a vector.','Score neighbors.','Select top-k.','Hand texts to the model.'],
      'FAQ deflection','Similar past answers retrieved for new tickets.','Neighbors suggest solutions.',
      [q('Similarity search returns…',['Nearest vectors/passages','Random GPUs','CSS files','DNS zones'],0,'Neighbors.'),q('Top-k means…',['Keep k best matches','Keep all internet','Delete k tokens','Train k epochs only'],0,'Best k.'),q('Cosine similarity cares a lot about…',['Vector direction','Cable color','Fan stickers','Mouse DPI'],0,'Direction/angle.')],
      ['similarity']),
    c('hybrid-search','Hybrid Search','Combine keywords and vectors','intermediate',7,['similarity-search'],
      'Hybrid search blends lexical matching (BM25/keywords) with vector similarity. Keywords catch exact IDs and rare terms; vectors catch paraphrases. Fusion methods merge ranked lists into a stronger candidate set.',
      'Using both the index at the back of a book and a librarian who understands meaning.',
      ['Run keyword and vector retrieval.','Fuse rankings.','Boost exact SKUs and codes.','Tune weights per corpus.','Often beats either alone.'],
      [['BM25','Classic lexical ranking'],['Fusion','Combine ranked lists'],['Exact match','Literal string hits']],
      ['Query has a SKU and a symptom.','Keyword finds the SKU doc.','Vector finds paraphrase guides.','Fusion merges.','Better candidates.'],
      'E-commerce support','Order IDs need keywords; fuzzy symptom descriptions need vectors.','Hybrid covers both.',
      [q('Hybrid search combines…',['Lexical and vector retrieval','Only images and audio','Loss and LR','Pods and nodes only'],0,'Both modes.'),q('Keywords help with…',['Exact IDs and rare tokens','Only poetry vibes','GPU voltage','Font kerning'],0,'Exactness.'),q('Vectors help with…',['Paraphrases','Only identical strings','HDMI hotplug','CSS :hover'],0,'Meaning.')],
      toggle(['Keywords only','Vectors only','Hybrid fusion'],{'Keywords only':'Misses paraphrases.','Vectors only':'May miss exact IDs.','Hybrid fusion':'Often best.'})),
    c('re-ranking','Re-ranking','Second-stage relevance sorting','intermediate',7,['hybrid-search'],
      'Re-ranking takes a broader candidate set from cheap retrieval and scores each query-document pair with a stronger model. It improves precision before the LLM sees context, at extra compute cost.',
      'A first pass grabs 50 library books quickly; an expert skims and keeps the best 5.',
      ['Retrieve many candidates cheaply.','Score pairs with a cross-encoder or LLM judge.','Keep top n.','Trade latency for precision.','Garbage in still limits quality.'],
      [['Cross-encoder','Model scoring a query-doc pair together'],['Precision','Are top results relevant?'],['Candidate generation','First-stage retrieval']],
      ['Retrieve top 50.','Re-rank with a stronger scorer.','Keep top 5.','Stuff into prompt.','Answer quality rises.'],
      'Legal research assistants','Re-rankers prioritize truly on-point case passages.','Precision matters under liability.',
      [q('Re-ranking is…',['Second-stage relevance sorting','Deleting the index','CSS minify','GPU overclocking'],0,'Rescoring.'),q('It usually follows…',['Cheap candidate retrieval','Model deletion','Font install','DNS flush'],0,'Two stages.'),q('Goal is higher…',['Precision of context','Temperature','Fan noise','Token prices always'],0,'Better top docs.')],
      toggle(['No rerank, stuff top 20','Rerank to top 5','Rerank with a random shuffle'],{'No rerank, stuff top 20':'Noisy context.','Rerank to top 5':'Common pattern.','Rerank with a random shuffle':'Useless.'})),
    c('context-budget','Context budget','Spend limited tokens wisely','intermediate',6,['re-ranking'],
      'The context budget is how many tokens you can afford for instructions, history, retrieved chunks, and the answer. RAG quality often hinges on what you include and exclude under that budget.',
      'A fixed-size suitcase: folding and choosing beats bringing the whole closet.',
      ['Measure token costs of each section.','Prefer high-signal chunks.','Compress or omit low-value history.','Leave room for the answer.','Monitor truncation bugs.'],
      [['Budget','Token capacity allocation'],['Truncation','Cutting overflow'],['High-signal','Evidence that changes the answer']],
      ['Count instruction tokens.','Add ranked chunks until budget.','Reserve answer space.','Generate.','Log what was dropped.'],
      'Mobile support bots','Smaller windows force aggressive chunk selection.','Budget discipline is product quality.',
      [q('Context budget is about…',['Limited tokens to allocate','Unlimited paste','GPU watts only','Cable length'],0,'Allocation.'),q('You should reserve space for…',['The answer generation','Nothing','Only ads','Only emojis'],0,'Completion room.'),q('Low-signal chunks should be…',['Deprioritized','Always included first','Used to replace instructions','Printed'],0,'Prioritize signal.')],
      toggle(['Stuff until overflow','Ranked fill with reserve','Empty retrieval'],{'Stuff until overflow':'Silent truncation risk.','Ranked fill with reserve':'Budget-aware.','Empty retrieval':'Under-grounded.'})),
    c('retrieval-pipeline','Retrieval pipeline','End-to-end RAG flow','intermediate',9,['context-budget'],
      'A retrieval pipeline chains ingest, chunk, embed, index, retrieve, (rerank), prompt assembly, generate, and cite. Production RAG is this pipeline plus evaluation and access control—not a single API call.',
      'A newsroom workflow: archive stories, index them, research for a question, then write with sources.',
      ['Offline path builds the index.','Online path answers a query.','Assembly builds the grounded prompt.','Citations map claims to chunks.','Evals measure retrieval and answer quality.'],
      [['Ingest','Load source documents'],['Prompt assembly','Build the grounded context'],['Citation','Link answer spans to sources']],
      ['Ingest docs.','Chunk and embed.','Query retrieves.','Rerank and assemble.','Generate grounded answer.'],
      'Internal wiki assistant','Pipeline refreshes nightly as wiki pages change.','Fresh index, same generator.',
      [q('RAG online path starts with…',['A user query','Deleting the index','CSS build','DNS renew'],0,'Query time.'),q('Prompt assembly…',['Builds grounded context for the LLM','Trains GPUs','Paints icons','Replaces chunking'],0,'Context build.'),q('Citations connect…',['Answers to sources','Fans to cases','Fonts to GPUs','Pods to CSS'],0,'Provenance.')],
      ['rag-query']),
    c('agentic-rag-intro','Agentic RAG intro','Retrieve iteratively with decisions','advanced',8,['retrieval-pipeline'],
      'Agentic RAG lets the model decide when and what to retrieve, possibly running multiple search steps, comparing sources, or asking clarifying questions. It is more flexible than one-shot retrieve-then-read, and more failure-prone without limits.',
      'A researcher who searches, reads, realizes a gap, searches again, then writes—not a single Google query.',
      ['Plan information needs.','Retrieve in loops.','Stop when enough evidence.','Needs tool budgets and audits.','Great for multi-hop questions.'],
      [['Multi-hop','Needs several facts chained'],['Tool budget','Max retrieval/actions'],['Stop condition','When to answer']],
      ['Question needs two facts.','First retrieval partial.','Agent plans second query.','Combines evidence.','Answers with sources.'],
      'Competitive research briefs','Agent pulls market notes then pricing pages before drafting.','Iteration finds multi-hop facts.',
      [q('Agentic RAG retrieves…',['Iteratively with decisions','Exactly once always','Never','Only images'],0,'Loops.'),q('A risk is…',['Unbounded tool loops','Perfect safety automatic','Free tokens','No need for ACLs'],0,'Control needed.'),q('Multi-hop questions often need…',['Multiple retrievals','One keyword only','No docs','CSS only'],0,'Several facts.')],
      ['agent-loop']),
    c('rag-failure-modes','RAG failure modes','Why grounded systems still fail','intermediate',8,['agentic-rag-intro'],
      'RAG fails when chunking is bad, embeddings miss, filters exclude the truth, context is noisy, the model ignores evidence, or citations are fabricated. Evaluate retrieval and generation separately.',
      'An open-book exam where you grab the wrong chapter, or read the right chapter and still misquote it.',
      ['Missed retrieval: answer has no chance.','Noisy context: model gets distracted.','Refusal to use evidence: ungrounded prose.','Stale indexes: outdated truth.','Measure recall@k and groundedness.'],
      [['Recall@k','Was the needed chunk in top k?'],['Groundedness','Claims supported by context'],['Index freshness','How up to date the store is']],
      ['Ask a known question.','Needed chunk missing.','Model invents.','Fix chunking/embeddings.','Answer becomes citable.'],
      'Wrong policy version served','Index lagged after handbook update; bot cited old leave days.','Freshness is a reliability feature.',
      [q('If retrieval misses, generation often…',['Hallucinates or abstains poorly','Becomes perfectly true','Speeds DNS','Fixes CSS'],0,'No evidence.'),q('Evaluate…',['Retrieval and generation separately','Only font size','Only GPU brand','Only cable length'],0,'Two stages.'),q('Fabricated citations are…',['A known failure mode','Impossible','Required','A vector metric'],0,'Must check.')],
      toggle(['No evals','Recall@k + groundedness checks','Trust all citations'],{'No evals':'Blind.','Recall@k + groundedness checks':'Healthy.','Trust all citations':'Dangerous.'})),
  ],

  'ai-agents': [
    c('ai-agent','AI Agent','A model that acts toward goals with tools','beginner',7,[],
      'An AI agent is a system that uses a model to pursue a goal by planning, calling tools, observing results, and updating state until it finishes or stops. It is more than a single reply; it is a loop with side effects.',
      'An intern with a checklist and phone access: think, call someone, update the checklist, repeat.',
      ['Goal-directed behavior.','Tools create real-world effects.','State tracks progress.','Needs limits and supervision.'],
      [['Agent','Goal-seeking loop with actions'],['Tool','External capability the agent can invoke'],['Side effect','Change outside the chat text']],
      ['Receive a goal.','Plan first action.','Call a tool.','Observe result.','Continue or finish.'],
      'Travel booking helper','Agent searches flights, compares, then drafts an itinerary.','Actions make it an agent.',
      [q('An agent typically…',['Acts in a loop with tools toward a goal','Only styles CSS','Only stores vectors','Only trains GPUs'],0,'Goal loop.'),q('Tools enable…',['Side effects and lookups','Nothing','Font bolding only','HDMI'],0,'Capabilities.'),q('Agents need…',['Limits and supervision','Infinite rights always','No logging','No goals'],0,'Control.')],
      toggle(['Single FAQ reply','Multi-step tool loop','Random button clicking'],{'Single FAQ reply':'Chatbot style.','Multi-step tool loop':'Agent style.','Random button clicking':'Unsafe chaos.'})),
    c('agentic-vs-chatbot','Agentic AI vs chatbot','Reply once versus act over time','beginner',6,['ai-agent'],
      'A chatbot mainly returns a next message. An agentic system can take multi-step actions, maintain state, and use tools across turns. Many products are hybrids: chat UI with optional agent modes for harder jobs.',
      'Answering a question at a help desk versus actually filing the ticket, checking status, and emailing you.',
      ['Chatbot: conversational response.','Agent: plans and acts.','Risk and cost rise with actions.','Pick the simplest mode that works.'],
      [['Chatbot','Conversational interface mostly without side effects'],['Agentic system','Multi-step tool-using autonomy'],['Human handoff','Escalate to a person']],
      ['User asks a simple definition.','Chat reply suffices.','User asks to book and email.','Agent mode engages tools.','Confirm before irreversible acts.'],
      'Banking assistant','Balances answered in chat; transfers require agentic flows plus approvals.','Match autonomy to risk.',
      [q('Chatbots mainly…',['Return conversational replies','Always file taxes','Manage Kubernetes by default','Train diffusion'],0,'Conversation.'),q('Agentic systems…',['Take multi-step actions','Never use tools','Forbid state','Only render CSS'],0,'Actions.'),q('Prefer…',['Simplest mode that works','Max autonomy always','No UX','No logs'],0,'Right-size autonomy.')],
      toggle(['Define HTTP','Book travel and email itinerary','Delete production DB'],{'Define HTTP':'Chat is enough.','Book travel and email itinerary':'Agentic candidate.','Delete production DB':'Danger—needs hard blocks.'})),
    c('plan-act-observe','Plan-Act-Observe loop','The heartbeat of agent behavior','beginner',7,['agentic-vs-chatbot'],
      'Most agents iterate: plan what to do, act via a tool or message, observe the outcome, then replan. This loop turns a static model into an interactive problem solver—and can loop forever without caps.',
      'Cooking while tasting: plan spice, act with a pinch, observe taste, adjust.',
      ['Plan proposes next step.','Act executes.','Observe captures result.','Update state and repeat.','Stop conditions are mandatory.'],
      [['Plan','Decide next action'],['Act','Execute tool/action'],['Observe','Read the result']],
      ['Goal set.','Plan an action.','Act.','Observe.','Replan or finish.'],
      'Data cleanup agent','Plans column fixes, runs scripts, observes errors, replans.','Loop drives progress.',
      [q('The core loop is…',['Plan, act, observe','Compile, link, only','Margin, padding, border','Ping, traceroute, only'],0,'PAO.'),q('Without stop conditions agents may…',['Loop forever','Become perfectly safe','Cool the room','Fix DNS forever'],0,'Caps needed.'),q('Observe feeds…',['The next plan','Only CSS','Only fonts','Only HDMI'],0,'Feedback.')],
      ['agent-loop']),
    c('agent-state','State','What the agent remembers between steps','intermediate',7,['plan-act-observe'],
      'State is structured memory the agent updates: goals, scratchpads, tool results, file pointers, and status flags. Good state design makes agents debuggable; stuffing everything into chat text alone becomes fragile.',
      'A pilot checklist and instrument panel—not only remembered conversation vibes.',
      ['Separate chat transcript from structured state.','Persist key fields.','Keep secrets out of prompts when possible.','Schema state enables recovery.'],
      [['State','Structured variables across steps'],['Scratchpad','Working notes'],['Checkpoint','Saved state snapshot']],
      ['Initialize state.','After each tool, update fields.','Next plan reads state.','Persist checkpoint.','Resume after failure.'],
      'Research agent folders','State tracks which sources were read and remaining questions.','Structure beats vibes.',
      [q('Agent state should be…',['Structured and updated each step','Only random prose always','Deleted every token','Stored in CSS'],0,'Structured.'),q('Checkpoints help…',['Resume after failures','Heat GPUs','Bold fonts','Route packets'],0,'Recovery.'),q('Secrets in prompts are…',['Risky','Required always','Impossible','A vector metric'],0,'Minimize exposure.')],
      toggle(['Only chat log','Typed state object','Global mutable everything'],{'Only chat log':'Fragile.','Typed state object':'Debuggable.','Global mutable everything':'Hard to audit.'})),
    c('planning','Planning','Decide the sequence before thrashing tools','intermediate',7,['agent-state'],
      'Planning decomposes a goal into steps before or between actions. Plans can be implicit in thoughts or explicit checklists. Overplanning wastes tokens; underplanning causes tool thrash.',
      'Writing grocery sections before wandering every aisle at random.',
      ['Clarify goal and constraints.','Decompose into steps.','Replan when observations invalidate assumptions.','Keep plans short and testable.','Share plan with users for trust.'],
      [['Plan','Ordered intended steps'],['Replan','Update plan after new info'],['Constraint','Hard limit on actions']],
      ['Goal arrives.','Draft a short plan.','Execute step 1.','Observation changes assumptions.','Replan remaining steps.'],
      'Migration agents','Plan schema changes before running migrations.','Look-ahead prevents disasters.',
      [q('Planning helps agents…',['Avoid random tool thrash','Delete evals','Ignore observations','Ban state'],0,'Structure.'),q('Replanning happens when…',['Observations invalidate assumptions','Fonts change','CSS hot-reloads','HDMI flickers'],0,'New info.'),q('Plans should be…',['Short and testable','Infinite novels','Secret from logs','Written only in emojis'],0,'Practical.')],
      toggle(['No plan, spam tools','Short checklist plan','100-page plan before hello world'],{'No plan, spam tools':'Thrash.','Short checklist plan':'Healthy.','100-page plan before hello world':'Overplanning.'})),
    c('memory','Memory','Persist useful information beyond one prompt','intermediate',8,['planning'],
      'Agent memory stores information across steps or sessions: conversation summaries, user preferences, retrieved facts, and episode logs. Memory systems must handle freshness, privacy, and relevance—or they become cluttered noise.',
      'Sticky notes, a diary, and a filing cabinet—not expecting perfect photographic recall every second.',
      ['Short-term: working context.','Long-term: stored notes/vectors.','Summarize to compress.','Forget stale or private items.','Retrieve memory like RAG.'],
      [['Short-term memory','Current working context'],['Long-term memory','Persisted knowledge store'],['Memory retrieval','Pull relevant notes into context']],
      ['Conversation grows.','Summarize older turns.','Store key preferences.','Later query retrieves memory.','Personalization with control.'],
      'Personal tutor memory','Remembers a student struggles with recursion and adapts examples.','Useful memory needs consent and controls.',
      [q('Memory helps agents…',['Use info beyond one prompt','Avoid all tools','Delete logs','Ban users'],0,'Persistence.'),q('Stale memory can…',['Mislead decisions','Only help','Cool GPUs','Fix CSS'],0,'Freshness matters.'),q('Memory retrieval is similar to…',['RAG over notes','HDMI negotiation','Font subsetting','DHCP only'],0,'Retrieve notes.')],
      toggle(['No memory','Summaries + preference store','Store every raw token forever'],{'No memory':'Stateless.','Summaries + preference store':'Practical.','Store every raw token forever':'Cost and privacy risk.'})),
    c('tools-tool-calling','Tools / Tool-calling','Let models invoke functions safely','intermediate',8,['memory'],
      'Tool-calling lets a model emit structured function calls that your runtime executes. Schemas describe arguments; the app returns observations. This is how models browse, calculate, or update systems—under your permission model.',
      'A voice assistant that can dial APIs the way you dial apps—only the ones you installed and allowed.',
      ['Declare tools with schemas.','Model selects and fills arguments.','Runtime executes and returns results.','Validate args and authenticate.','Never expose unconstrained shell by default.'],
      [['Tool schema','Name, description, parameters'],['Function call','Structured invocation'],['Allowlist','Permitted tools only']],
      ['User asks for weather.','Model calls weather tool.','Runtime fetches data.','Observation returns.','Model answers with facts.'],
      'Calendar assistants','Create-event tool with OAuth scopes.','Permissions make tools safe enough to ship.',
      [q('Tool-calling emits…',['Structured function calls','Random poetry only','CSS only','GPU microcode'],0,'Functions.'),q('Schemas define…',['Parameters and types','Ocean salinity','Fan curves','Mouse LOD'],0,'Contracts.'),q('Unconstrained shell access is…',['Dangerous by default','Always required','A vector DB','A font'],0,'Avoid.')],
      toggle(['No tools','Allowlisted tools with auth','Root shell tool for everyone'],{'No tools':'Language only.','Allowlisted tools with auth':'Production pattern.','Root shell tool for everyone':'Incident waiting.'}),
      ['ts','Tool schema sketch','{ name: "weather", parameters: { city: "string" } }','Validate before execute.']),
    c('react-agents','ReAct agents','Agents that think and act in text traces','intermediate',9,['tools-tool-calling'],
      'ReAct agents operationalize the Thought-Action-Observation pattern as a runtime loop with tools. Traces make debugging easier, but verbose thoughts can leak private reasoning and cost tokens.',
      'A detective notebook: hypothesize, check a clue, write what was found, hypothesize again.',
      ['Emit thought.','Emit action.','Runtime provides observation.','Repeat with budgets.','Parse carefully; models drift from format.'],
      [['Trace','Visible thought/action log'],['Budget','Max steps/tokens/tools'],['Parser','Extract actions reliably']],
      ['Goal: weather-based outfit.','Thought needs weather.','Action calls API.','Observation: 32C sunny.','Final recommendation.'],
      'Ops runbooks','Agents follow ReAct to query metrics then suggest mitigations.','Traces aid incident review.',
      [q('ReAct agents interleave…',['Thoughts and tool actions','Only embeddings','Only CSS','Only epochs'],0,'TAO.'),q('Budgets prevent…',['Runaway loops','All learning','Tokenization','JSON'],0,'Caps.'),q('Traces help…',['Debugging','Overheating intentionally','Deleting indexes','Hiding audits'],0,'Visibility.')],
      ['agent-loop']),
    c('multi-agent','Multi-agent','Several specialized agents collaborating','advanced',8,['react-agents'],
      'Multi-agent systems assign roles to multiple agents—researcher, coder, critic—that communicate. Specialization can improve quality, but coordination overhead, cost, and failure modes grow quickly.',
      'A small studio: writer, editor, and fact-checker instead of one exhausted generalist.',
      ['Split roles clearly.','Define communication protocols.','Avoid infinite debate loops.','Centralize shared state carefully.','Measure if multi-agent beats a single strong agent.'],
      [['Role','Specialized agent responsibility'],['Protocol','How agents message'],['Orchestration','Who speaks when']],
      ['Manager assigns roles.','Researcher gathers.','Writer drafts.','Critic reviews.','Merge final output.'],
      'Software PR agents','One agent writes tests, another reviews security.','Specialization mirrors teams.',
      [q('Multi-agent means…',['Multiple specialized collaborating agents','Multiple GPUs only','Multiple CSS files','Multiple DNS servers only'],0,'Roles.'),q('A risk is…',['Coordination overhead and loops','Guaranteed cheaper always','No need for evals','Perfect safety'],0,'Overhead.'),q('You should check…',['Whether one agent suffices','That debate never ends','That logs are off','That tools are root'],0,'Justify complexity.')],
      toggle(['One general agent','Researcher + writer + critic','Ten agents arguing forever'],{'One general agent':'Simple baseline.','Researcher + writer + critic':'Common pattern.','Ten agents arguing forever':'Failure mode.'})),
    c('supervisor-pattern','Supervisor pattern','A manager agent routes work','advanced',7,['multi-agent'],
      'In the supervisor pattern, a central agent routes subtasks to worker agents, aggregates results, and decides next steps. It simplifies control flow compared with fully peer-to-peer swarms.',
      'A shift manager assigning tickets to specialists and combining their results.',
      ['Supervisor plans and routes.','Workers execute narrow skills.','Supervisor merges outputs.','Clear ownership of stop/fail.','Good fit for tool-specialist farms.'],
      [['Supervisor','Orchestrating agent'],['Worker','Specialized agent'],['Handoff','Passing a subtask']],
      ['User goal to supervisor.','Route to retrieval worker.','Route to drafting worker.','Supervisor reviews.','Final response.'],
      'Customer ops suites','Supervisor sends billing questions to billing tools agent.','Routing clarifies ownership.',
      [q('Supervisor pattern uses…',['A central router agent','No orchestration','Only peer chaos','Only CSS'],0,'Central control.'),q('Workers should be…',['Specialized','Omnipotent root shells','Silent forever','Unlogged'],0,'Narrow skills.'),q('Supervisor owns…',['Stop/fail decisions often','Nothing','Only fonts','Only HDMI'],0,'Control plane.')],
      toggle(['Peer swarm with no owner','Supervisor + workers','Everyone can call everyone with no limits'],{'Peer swarm with no owner':'Harder to control.','Supervisor + workers':'Clearer orchestration.','Everyone can call everyone with no limits':'Chaos.'})),
    c('guardrails','Guardrails','Hard rails around soft models','intermediate',7,['supervisor-pattern'],
      'Guardrails are checks that constrain inputs, tools, and outputs: allowlists, policy classifiers, regex validators, rate limits, and human approvals. They acknowledge that prompts alone are soft.',
      'Guardrails on a mountain road: the driver still steers, but barriers prevent falling off cliffs.',
      ['Validate inputs.','Constrain tools.','Filter outputs.','Fail closed on high risk.','Log violations for review.'],
      [['Allowlist','Only permitted operations'],['Policy filter','Blocks disallowed content'],['Fail closed','Deny when unsure on high risk']],
      ['User input arrives.','Input guard runs.','Agent acts within tool allowlist.','Output filter checks.','Safe response ships.'],
      'PII redaction filters','Outputs scrub account numbers before chat display.','Defense in depth.',
      [q('Guardrails are…',['Hard checks around model behavior','Only system prompt poetry','GPU fans','CSS variables'],0,'Hard checks.'),q('Fail closed means…',['Deny when unsure on high risk','Allow everything','Delete logs','Raise temperature'],0,'Safe default.'),q('Tool allowlists…',['Limit capabilities','Grant root always','Remove auth','Ban schemas'],0,'Least privilege.')],
      toggle(['Prompt-only safety','Allowlists + validators + logs','No logging of violations'],{'Prompt-only safety':'Soft.','Allowlists + validators + logs':'Stronger.','No logging of violations':'Cannot improve.'})),
    c('mcp-conceptual','MCP (conceptual)','A standard way to plug tools and context','intermediate',7,['guardrails'],
      'Model Context Protocol (MCP) is a conceptual standard for exposing tools, resources, and prompts to models through a consistent interface. The idea is portable capabilities: connect an IDE, docs server, or database gateway without bespoke glue each time.',
      'USB for AI tools: a common plug so many accessories work with many hosts.',
      ['Hosts connect to MCP servers.','Servers expose tools/resources.','Models call tools via the host.','Permissions still belong to your app.','Standards reduce integration sprawl.'],
      [['MCP host','App that connects to servers'],['MCP server','Exposes tools/resources'],['Resource','Readable context object']],
      ['Host starts.','Connects to a docs MCP server.','Lists tools/resources.','Model invokes read/search.','Observation returns.'],
      'IDE copilots','A repo tools server exposes test runners and file readers via a shared protocol.','Portable tool ecosystems emerge.',
      [q('MCP is conceptually…',['A standard interface for tools/context','A GPU brand','A CSS framework','A loss function'],0,'Protocol idea.'),q('Permissions still…',['Belong to your application','Disappear','Belong to temperature','Belong to cosine'],0,'App owns authz.'),q('Servers expose…',['Tools and resources','Only wallpapers','Only HDMI','Only fan curves'],0,'Capabilities.')],
      toggle(['Custom one-off tool glue each time','Shared protocol for tools','Give model raw cloud root keys'],{'Custom one-off tool glue each time':'Sprawl.','Shared protocol for tools':'MCP-style portability.','Give model raw cloud root keys':'Unsafe.'})),
    c('hitl','HITL','Human-in-the-loop approvals','beginner',6,['mcp-conceptual'],
      'Human-in-the-loop (HITL) inserts people at critical steps: approve spends, edit drafts, confirm deletions. Autonomy handles draft work; humans own irreversible or regulated actions.',
      'Autopilot can fly, but a pilot takes over for landing in a storm.',
      ['Identify high-risk actions.','Pause for approval.','Show evidence and diffs.','Record who approved.','Tune which steps need humans.'],
      [['Approval gate','Pause for human decision'],['Escalation','Route to an expert'],['Audit trail','Who did what when']],
      ['Agent drafts a money transfer.','HITL gate pauses.','Human reviews.','Approve or reject.','Continue safely.'],
      'Refund agents','Auto-approve tiny refunds; humans approve large ones.','Risk-based autonomy.',
      [q('HITL means…',['Humans approve critical steps','Humans never involved','Only models approve','No logs'],0,'Human gates.'),q('Use HITL especially for…',['Irreversible or high-risk actions','Changing font size','Ping latency','CSS hover color'],0,'Risk.'),q('Audit trails record…',['Approvals and actions','Nothing','Only GPU temps','Only wallpapers'],0,'Accountability.')],
      toggle(['Auto-send all emails','Approve outbound customer emails','Human types every token'],{'Auto-send all emails':'Risky.','Approve outbound customer emails':'Practical HITL.','Human types every token':'No leverage.'})),
    c('checkpointing','Checkpointing','Save progress to recover and audit','intermediate',6,['hitl'],
      'Checkpointing snapshots agent state after steps so runs can resume, branch, or audit. It is essential for long jobs and for replaying failures without redoing expensive tool calls.',
      'Video game save points before boss fights.',
      ['Snapshot state and outputs.','Resume from last good point.','Support time-travel debugging.','Store securely with retention policies.','Combine with idempotent tools.'],
      [['Checkpoint','Saved snapshot'],['Resume','Continue from snapshot'],['Idempotent tool','Safe to retry']],
      ['Start long research.','Checkpoint after each source.','Crash occurs.','Resume from last checkpoint.','Finish without full redo.'],
      'ETL agent jobs','Nightly agents checkpoint after each table migration step.','Recovery beats reruns.',
      [q('Checkpointing enables…',['Resume and audit','Hotter GPUs','Bolder fonts','Faster light'],0,'Recovery.'),q('Idempotent tools help because…',['Retries are safer','Retries are impossible','Logs are banned','Schemas vanish'],0,'Safe retry.'),q('Checkpoints should be…',['Stored with security/retention in mind','Posted publicly always','Deleted every millisecond','Written in CSS only'],0,'Govern them.')],
      toggle(['No saves','Checkpoint each major step','Checkpoint every keystroke to public S3'],{'No saves':'Fragile long jobs.','Checkpoint each major step':'Practical.','Checkpoint every keystroke to public S3':'Privacy disaster.'})),
    c('agent-failure-modes','Agent failure modes','How autonomy breaks','intermediate',8,['checkpointing'],
      'Agents fail via loops, tool misuse, prompt injection from tool outputs, goal misinterpretation, cost explosions, and silent partial completion. Design budgets, validators, and evaluations for agent traces—not only final answers.',
      'A well-meaning intern endlessly emailing the wrong distribution list because nobody set a stop rule.',
      ['Unbounded retries.','Trusting malicious tool text as instructions.','Wrong success criteria.','Missing HITL on irreversible acts.','Trace evals catch patterns.'],
      [['Prompt injection','Malicious instructions in data/tools'],['Looping','Repeating actions without progress'],['Partial completion','Stops mid-goal unnoticed']],
      ['Agent reads a web page.','Page says ignore policies.','Without guards, agent complies.','Injection succeeds.','Sanitize and isolate tool text.'],
      'Web-using agents','Untrusted pages attempted to override system rules.','Treat tool outputs as untrusted data.',
      [q('Tool outputs should be treated as…',['Untrusted data','Root commands','Always safe system prompts','CSS variables'],0,'Untrusted.'),q('Budgets mitigate…',['Cost and loop explosions','All hallucinations forever','Need for auth','Need for tests'],0,'Caps.'),q('Evaluate…',['Traces and outcomes','Only final marketing copy','Only GPU stickers','Only fonts'],0,'Agent evals.')],
      toggle(['Trust all web text as system','Isolate tool text + budgets','Infinite retries'],{'Trust all web text as system':'Injection bait.','Isolate tool text + budgets':'Hardening.','Infinite retries':'Cost bomb.'})),
  ],

  'ai-frameworks': [
    c('langchain','LangChain','Composable chains and tool wrappers','beginner',6,[],
      'LangChain is a popular framework for composing prompts, retrievers, tools, and memory into LLM applications. Conceptually it standardizes building blocks so you can assemble RAG and agents faster—while still owning evaluation and architecture choices.',
      'A box of LEGO adapters for LLM apps: useful accelerators, not a substitute for design.',
      ['Chains compose steps.','Integrations wrap many vendors.','Abstractions can hide costs/complexity.','Great for prototypes; mind lock-in and opacity.'],
      [['Chain','Pipeline of LLM steps'],['Integration','Connector to a vendor/tool'],['Runnable','Composable unit of work']],
      ['Define a prompt.','Add a retriever.','Call an LLM.','Parse output.','Ship a thin app.'],
      'Weekend RAG demo','Students wire PDF loader → split → vectorstore → QA chain quickly.','Speed for learning and spikes.',
      [q('LangChain is mainly…',['A composition framework for LLM apps','A GPU','A CSS engine','A vector metric'],0,'Framework.'),q('A risk of heavy abstraction is…',['Hidden complexity and cost','Guaranteed correctness','Free hosting','No need for evals'],0,'Opacity.'),q('It often helps…',['Prototype RAG/agents faster','Replace all databases','Ban Python','Delete prompts'],0,'Speed.')],
      toggle(['Raw SDK only','LangChain-style composition','Framework with zero observability'],{'Raw SDK only':'More control.','LangChain-style composition':'Faster assembly.','Framework with zero observability':'Hard to debug.'})),
    c('langgraph','LangGraph','Graph-based agent control flow','intermediate',7,['langchain'],
      'LangGraph models agent workflows as graphs with nodes, edges, and explicit state—useful for durable, branching, human-in-the-loop agent systems beyond linear chains.',
      'A flowchart you can execute: boxes are steps, arrows are decisions, and sticky notes are state.',
      ['State is first-class.','Graphs support cycles and branches.','Good for durable agents.','More structure than free-form loops.'],
      [['Node','A computation step'],['Edge','Transition between steps'],['Durable execution','Resume-friendly runs']],
      ['Define state schema.','Add nodes for retrieve/act/approve.','Connect edges.','Compile graph.','Run with checkpoints.'],
      'Approval-heavy ops bots','Graph pauses on HITL nodes then resumes.','Control flow matches business process.',
      [q('LangGraph emphasizes…',['Graph control flow and state','Only CSS grids','Only cosine','Only HDMI'],0,'Graphs.'),q('Cycles in graphs enable…',['Agent loops','Perfect truth','Free GPUs','No state'],0,'Loops.'),q('Durable execution helps…',['Resume long runs','Delete logs','Ban approvals','Avoid schemas'],0,'Recovery.')],
      toggle(['Linear chain only','Stateful graph with HITL node','Spaghetti callbacks'],{'Linear chain only':'Simple paths.','Stateful graph with HITL node':'LangGraph sweet spot.','Spaghetti callbacks':'Hard to reason.'})),
    c('llamaindex','LlamaIndex','Data framework for LLM retrieval apps','beginner',6,['langgraph'],
      'LlamaIndex focuses on connecting LLMs to data: indexes, query engines, and retrieval abstractions. Conceptually reach for it when your core problem is document QA and structured data access patterns.',
      'A librarian toolkit specialized for getting the right pages into the model’s hands.',
      ['Indexes over documents and more.','Query engines encapsulate retrieval+synthesis.','Strong fit for RAG-centric apps.','Still needs evals for faithfulness.'],
      [['Index','Data structure for retrieval'],['Query engine','Retrieval plus answer interface'],['Node parser','Chunking component']],
      ['Load documents.','Build an index.','Create a query engine.','Ask questions.','Return grounded answers.'],
      'Course material tutors','Index lecture PDFs for student questions.','Data-first framework fit.',
      [q('LlamaIndex is especially known for…',['Data/RAG indexing patterns','Painting icons','Training GPUs from CSS','DHCP'],0,'Data framework.'),q('A query engine typically…',['Retrieves and synthesizes answers','Only trains diffusion','Only styles buttons','Only pings hosts'],0,'RAG interface.'),q('You still need…',['Evaluation of groundedness','Zero tests','No chunking','No metadata'],0,'Evals remain.')],
      toggle(['Chat with no docs','Index docs + query engine','Fine-tune for every FAQ edit'],{'Chat with no docs':'Ungrounded.','Index docs + query engine':'LlamaIndex-style.','Fine-tune for every FAQ edit':'Heavy-handed.'})),
    c('crewai','CrewAI','Role-playing multi-agent crews','intermediate',6,['llamaindex'],
      'CrewAI popularizes multi-agent “crews” with roles, tasks, and collaboration patterns. Conceptually it is an orchestration layer for role-based agent teams, with the usual multi-agent tradeoffs.',
      'Assigning producer, writer, and editor roles on a small film set.',
      ['Define agents with roles.','Assign tasks.','Orchestrate collaboration.','Watch cost and loops.','Validate outputs per role.'],
      [['Crew','Team of agents'],['Task','Unit of work'],['Role','Persona and responsibilities']],
      ['Create researcher agent.','Create writer agent.','Assign tasks to crew.','Collaborate.','Emit final deliverable.'],
      'Content pipelines','Researcher gathers sources; writer drafts; editor polishes.','Roles mirror human teams.',
      [q('CrewAI centers on…',['Role-based multi-agent teams','Only vector math','Only Kubernetes','Only CSS'],0,'Crews.'),q('A key tradeoff is…',['Coordination cost','Guaranteed cheaper answers','No need for tools','Perfect safety'],0,'Overhead.'),q('Tasks should be…',['Clear per role','Infinite and vague','Secret from logs','Unowned'],0,'Clarity.')],
      toggle(['Single agent draft','Crew with researcher+writer','Twenty agents rewrite forever'],{'Single agent draft':'Simple.','Crew with researcher+writer':'Crew-style.','Twenty agents rewrite forever':'Waste.'})),
    c('autogen','AutoGen','Multi-agent conversation frameworks','intermediate',6,['crewai'],
      'AutoGen (and similar systems) structure multi-agent applications as conversations between agents—including user proxies and tool-using assistants. The conversation metaphor makes patterns easy to sketch and easy to overcomplicate.',
      'A group chat where each participant has a job and can call tools when needed.',
      ['Agents message each other.','User proxy can represent humans/tools.','Conversation policies control turns.','Needs termination conditions.'],
      [['User proxy','Agent representing user/side effects'],['Assistant agent','LLM-backed participant'],['Termination','When chat stops']],
      ['User proxy posts a goal.','Assistant proposes a plan.','Tool calls execute.','Agents discuss results.','Terminate with answer.'],
      'Coding helper groups','One agent writes code; another runs tests via tools.','Conversation drives iteration.',
      [q('AutoGen-style systems often model…',['Agents as conversing participants','Only CSS grids','Only cosine distance','Only HDMI'],0,'Conversations.'),q('Termination conditions…',['Stop runaway chats','Invite infinite loops','Delete tools','Ban state'],0,'Stops.'),q('User proxies can…',['Represent humans or tool sides','Replace electricity','Paint SVGs','Set DNS'],0,'Bridge roles.')],
      toggle(['Solo LLM call','Multi-agent conversation with termination','Infinite agent debate'],{'Solo LLM call':'Minimal.','Multi-agent conversation with termination':'AutoGen-like.','Infinite agent debate':'Failure.'})),
    c('google-adk','Google ADK','Agent development kit mindset','intermediate',6,['autogen'],
      'Agent Development Kits (such as Google’s ADK conceptually) package patterns for building, evaluating, and deploying agents with cloud-native integrations. Think batteries-included tooling around orchestration, tools, and ops—not a new model architecture.',
      'A robotics starter kit: motors, sensors, and manuals so you build a robot faster than inventing parts.',
      ['Opinionated agent scaffolding.','Cloud integrations nearby.','Emphasis on tooling and lifecycle.','Portability varies by kit.'],
      [['ADK','Agent development kit'],['Scaffolding','Starter structure'],['Lifecycle','Build, eval, deploy, monitor']],
      ['Scaffold an agent project.','Wire tools.','Add eval harness.','Deploy to cloud runtime.','Monitor traces.'],
      'Enterprise agent platforms','Kits standardize how teams ship internal agents.','Shared scaffolding beats one-offs.',
      [q('An ADK is mainly…',['Scaffolding and tools for building agents','A tokenizer','A loss curve','A font'],0,'Dev kit.'),q('Kits often include…',['Lifecycle and integration helpers','Guaranteed AGI','Free unlimited tokens','No need for auth'],0,'Lifecycle.'),q('Portability…',['May vary by vendor kit','Is always perfect','Is irrelevant','Means no logs'],0,'Mind lock-in.')],
      toggle(['From-scratch agent runtime','ADK-style scaffold','Copy a random notebook forever'],{'From-scratch agent runtime':'Max control.','ADK-style scaffold':'Faster standards.','Copy a random notebook forever':'Fragile.'})),
    c('litellm','LiteLLM','One interface across many model APIs','beginner',5,['google-adk'],
      'LiteLLM provides a unified API layer to call many LLM vendors with similar request shapes. Conceptually it reduces glue code when you want provider failover, routing, or simpler swaps—while you still handle prompts and safety.',
      'A universal remote that speaks many TV brands’ dialects.',
      ['Normalize chat completion calls.','Route across providers.','Helpful for failover and cost routing.','Does not solve evaluation by itself.'],
      [['Provider','Model vendor/API'],['Routing','Choose which model/endpoint'],['Failover','Switch on errors']],
      ['App calls unified API.','LiteLLM-style router selects provider.','Request translated.','Response normalized.','App continues.'],
      'Multi-cloud copilots','Teams fail over when one vendor rate-limits.','Indirection buys resilience.',
      [q('LiteLLM-style layers…',['Unify many model APIs','Train diffusion','Replace vector DBs','Compile CSS'],0,'Unified API.'),q('Useful for…',['Routing and failover','Guaranteeing truth','Deleting prompts','Removing auth'],0,'Ops flexibility.'),q('You still must…',['Design prompts and safety','Do nothing','Ban logging','Ignore costs'],0,'App logic remains.')],
      toggle(['Hardcode one vendor SDK','Unified router across vendors','Call every vendor for every token blindly'],{'Hardcode one vendor SDK':'Simple, less portable.','Unified router across vendors':'LiteLLM-like.','Call every vendor for every token blindly':'Wasteful.'})),
    c('framework-comparison','When to use what','Choose tools by job, not hype','intermediate',8,['litellm'],
      'Pick frameworks by your bottleneck: raw SDK for control, LangChain for composable prototypes, LangGraph for durable agent graphs, LlamaIndex for data/RAG-centric apps, multi-agent kits for role workflows, LiteLLM for provider portability. The winning choice is the thinnest stack you can operate.',
      'Choosing kitchen tools: a chef’s knife covers most jobs; buy a pasta machine only if you make pasta weekly.',
      ['Start from the problem.','Prefer thin wrappers early.','Add orchestration when state gets hard.','Standardize observability regardless of framework.','Re-evaluate when requirements change.'],
      [['Thin stack','Fewer abstractions'],['Bottleneck','What actually slows delivery'],['Operability','Can your team run it?']],
      ['Define the job.','Map to framework strengths.','Spike two options.','Compare debuggability.','Choose and document.'],
      'Student capstone choices','RAG FAQ → LlamaIndex/light RAG; HITL agent → graph; multi-provider → LiteLLM.','Match tool to task.',
      [q('Choose frameworks by…',['Job and operability','Only Twitter hype','GPU sticker color','Font fashion'],0,'Fit.'),q('Thin stacks help…',['Early clarity and control','Guaranteed scale forever','Skip evals','Skip auth'],0,'Simplicity.'),q('Observability should be…',['Present regardless of framework','Optional forever','Replaced by vibes','Banned'],0,'Always.')],
      toggle(['RAG FAQ bot','Durable HITL agent','Multi-provider routing'],{'RAG FAQ bot':'Data/RAG-focused tools.','Durable HITL agent':'Graph/stateful orchestration.','Multi-provider routing':'Unified API layer.'})),
  ],

  deployment: [
    c('llm-app-serving','LLM app serving mental model','Clients talk to your app, app talks to models','beginner',7,[],
      'Serving an LLM app usually means your backend receives user requests, applies auth and policies, builds prompts/context, calls a model endpoint, streams tokens back, and logs traces. The model may be hosted by you or a cloud provider.',
      'A restaurant: customers talk to waiters (your API), kitchen (model) cooks, food comes out in courses (streams).',
      ['Client → API → orchestration → model.','Keep secrets server-side.','Separate product logic from model vendor.','Design for timeouts and partial failures.'],
      [['Endpoint','Network API your clients call'],['Orchestration','Prompt/RAG/tool logic'],['Model inference','Generating tokens']],
      ['Client sends request.','API authenticates.','Orchestration builds context.','Model generates.','Response streams back.'],
      'Campus tutor SaaS','Web UI hits a FastAPI service that calls a hosted LLM with RAG.','Your app is the product boundary.',
      [q('Clients should usually call…',['Your app API','Your raw cloud keys in the browser','The GPU directly via USB','Random IPs'],0,'App boundary.'),q('Secrets belong…',['Server-side','In frontend bundles','In screenshots','In CSS'],0,'Server.'),q('Orchestration includes…',['Prompt/RAG/tool logic','Only HDMI','Only fonts','Only fan curves'],0,'App brain.')],
      toggle(['Browser holds API keys','Server-side orchestration','No timeouts'],{'Browser holds API keys':'Leak risk.','Server-side orchestration':'Proper.','No timeouts':'Hung UX.'})),
    c('fastapi-role','FastAPI role','Python APIs that orchestrate LLM calls','beginner',6,['llm-app-serving'],
      'FastAPI is a popular Python web framework for building async APIs—commonly used as the orchestration layer for LLM apps: routes, auth, validation, and streaming responses. Conceptually any solid API framework can play this role.',
      'The waiter station: takes orders in a standard format and coordinates the kitchen.',
      ['Define request/response schemas.','Implement orchestration routes.','Stream tokens over HTTP.','Validate inputs.','Not the model itself—just the app layer.'],
      [['Route','URL handler'],['Pydantic model','Request validation schema'],['Streaming response','Send tokens incrementally']],
      ['Define /chat route.','Validate body.','Call model provider.','Stream tokens.','Log trace id.'],
      'Hackathon backends','Students expose /ask endpoints wrapping OpenAI-compatible APIs.','Fast iteration API layer.',
      [q('FastAPI often serves as…',['The orchestration API layer','The GPU silicon','The tokenizer hardware','The vector math unit'],0,'API layer.'),q('It is…',['Not the LLM itself','Always a vector DB','A CSS framework','A loss function'],0,'App server.'),q('Streaming responses help…',['Perceived latency','Delete logs','Ban JSON','Cool rooms'],0,'UX.')],
      toggle(['Monolith notebook exposed publicly','Typed API routes','No input validation'],{'Monolith notebook exposed publicly':'Fragile/unsafe.','Typed API routes':'Solid.','No input validation':'Injection and crashes.'})),
    c('docker','Docker','Package the app and its dependencies','beginner',6,['fastapi-role'],
      'Docker packages your application, runtime, and dependencies into images that run as containers. For LLM apps, containers make API services portable across laptops and clouds—while model weights may still live on volumes or remote APIs.',
      'A shipping container for software: same box runs on different ships (machines).',
      ['Write a Dockerfile.','Build an image.','Run a container.','Pin dependency versions.','Keep secrets out of images.'],
      [['Image','Immutable package'],['Container','Running instance'],['Dockerfile','Build recipe']],
      ['App code ready.','Build image.','Run container locally.','Same image in staging.','Promote to prod.'],
      'Identical tutor API envs','“Works on my machine” fades when classmates run the same image.','Portability aids teamwork.',
      [q('Docker packages…',['App and dependencies','Ocean water','Only CSS','Only HDMI'],0,'Images.'),q('Secrets should be…',['Injected at runtime, not baked in','Committed in Dockerfiles','Printed on labels','Stored in wallpapers'],0,'Runtime secrets.'),q('Containers help…',['Portable deploys','Guaranteed model quality','Infinite context','Free GPUs'],0,'Ops portability.')],
      toggle(['Works on my machine only','Containerized API','Bake API keys into the image'],{'Works on my machine only':'Fragile.','Containerized API':'Portable.','Bake API keys into the image':'Leak risk.'})),
    c('kubernetes-overview','Kubernetes overview','Orchestrate many containers','intermediate',7,['docker'],
      'Kubernetes (K8s) schedules and manages containers across machines: deploy replicas, restart crashes, expose services, and scale. LLM apps may put API replicas on K8s while inference runs on GPU nodes or external APIs.',
      'An air-traffic control system for containers—landing, scaling, and restarting workloads.',
      ['Pods run containers.','Deployments manage replicas.','Services provide networking.','Autoscaling reacts to load.','Complexity must be justified.'],
      [['Pod','Smallest schedulable unit'],['Deployment','Replica management'],['Service','Stable network endpoint']],
      ['Build container image.','Declare Deployment.','Expose Service.','Scale on load.','Rolling update.'],
      'Campus cloud club','API autoscales during exam week traffic spikes.','Orchestration absorbs load.',
      [q('Kubernetes mainly…',['Orchestrates containers','Trains models by itself','Replaces prompts','Paints UI'],0,'Orchestration.'),q('A Deployment manages…',['Replicas of your pods','Font files','HDMI cables','Cosine scores'],0,'Replicas.'),q('Use K8s when…',['You need scalable container ops','You only have a static HTML file','You hate logs','You need no networking'],0,'Justify complexity.')],
      toggle(['Single VM docker run','K8s for multi-replica API','K8s for a 5-person static site'],{'Single VM docker run':'Fine at small scale.','K8s for multi-replica API':'Fits growth.','K8s for a 5-person static site':'Overkill.'})),
    c('bedrock','Bedrock','Managed foundation models on AWS','beginner',5,['kubernetes-overview'],
      'Amazon Bedrock is a managed service to call foundation models via AWS APIs without self-hosting GPUs. Conceptually: provider-hosted inference with cloud IAM, networking, and billing integrated into AWS.',
      'Ordering kitchen output from a hotel that already runs industrial kitchens—you bring recipes (prompts), they run stoves.',
      ['Invoke models through AWS APIs.','IAM controls access.','Useful when already on AWS.','Still build your orchestration and RAG.'],
      [['Managed inference','Provider runs the model servers'],['IAM','Identity and access management'],['Invocation','API call to generate']],
      ['App authenticates to AWS.','Calls Bedrock invoke API.','Receives generations.','Logs to CloudWatch.','Pays per usage.'],
      'Enterprise AWS shops','Teams adopt Bedrock to stay inside existing AWS controls.','Cloud gravity matters.',
      [q('Bedrock provides…',['Managed model access on AWS','A CSS framework','A local tokenizer chip','A vector proof'],0,'Managed models.'),q('You still need…',['Your app orchestration','Zero auth','No monitoring','No prompts'],0,'App remains.'),q('Access is typically governed by…',['IAM policies','Wallpaper color','Fan stickers','Mouse DPI'],0,'IAM.')],
      toggle(['Self-host all GPUs','Managed Bedrock-like API','Browser-embedded cloud keys'],{'Self-host all GPUs':'Ops heavy.','Managed Bedrock-like API':'Faster path on AWS.','Browser-embedded cloud keys':'Leak.'})),
    c('vertex-ai','Vertex AI','Google Cloud ML/LLM platform','beginner',5,['bedrock'],
      'Vertex AI is Google Cloud’s platform for ML and generative AI services—model APIs, tooling, and MLOps integrations. Conceptually similar tradeoff: managed capabilities inside a cloud ecosystem versus self-hosting.',
      'A city workshop district with shared power tools—you build products using the district’s infrastructure.',
      ['Managed generative APIs.','Ties into GCP IAM and networking.','MLOps tooling nearby.','Orchestration still your job.'],
      [['Vertex AI','GCP ML/GenAI platform'],['Managed API','Hosted model endpoint'],['MLOps','Operate ML systems in prod']],
      ['Enable Vertex APIs.','Call a generative endpoint.','Wire results into app.','Monitor usage.','Iterate prompts/evals.'],
      'GCP-native startups','Use Vertex model APIs with BigQuery-stored logs.','Ecosystem integration.',
      [q('Vertex AI is…',['GCP’s ML/GenAI platform','A CSS reset','A HDMI switch','A cosine formula'],0,'GCP platform.'),q('Managed endpoints reduce…',['Self-host inference ops','Need for evals','Need for auth','Need for UX'],0,'Ops relief.'),q('Your app still handles…',['Product logic and safety','Silicon design','Ocean cooling','Font casting'],0,'Product layer.')],
      toggle(['DIY GPU cluster first day','Managed Vertex-like APIs','Skip monitoring'],{'DIY GPU cluster first day':'Slow start.','Managed Vertex-like APIs':'Faster on GCP.','Skip monitoring':'Blind.'})),
    c('azure-ai','Azure AI','Microsoft cloud AI services','beginner',5,['vertex-ai'],
      'Azure AI services provide managed model and AI capability APIs in Microsoft’s cloud, often attractive to enterprises already on Azure and Microsoft identity. Same mental model: managed inference plus your orchestration.',
      'Building inside an office park that already has power, security badges, and utilities.',
      ['Managed model endpoints.','Enterprise identity integrations.','Region and compliance options.','Your RAG/agents remain custom.'],
      [['Azure OpenAI / Azure AI','Managed model offerings on Azure'],['Entra ID','Microsoft identity platform'],['Compliance','Regional/policy constraints']],
      ['Authenticate with Azure identity.','Call model deployment.','Apply enterprise policies.','Log to Azure Monitor.','Ship features.'],
      'Corp Copilot add-ons','Enterprises host approved deployments on Azure.','Identity and compliance drive cloud choice.',
      [q('Azure AI appeals when…',['You are invested in Microsoft cloud/identity','You need a CSS framework','You hate APIs','You only train locally always'],0,'Ecosystem fit.'),q('Managed deployments still need…',['App-side safety and evals','No logging','Public keys in mobile apps','Zero auth'],0,'Responsibility remains.'),q('Identity integrations help…',['Enterprise access control','Bold fonts','Cool GPUs','Shorter cables'],0,'Access.')],
      toggle(['Ignore enterprise identity','Use cloud identity with managed models','Share one key in Slack'],{'Ignore enterprise identity':'Hard in corps.','Use cloud identity with managed models':'Enterprise fit.','Share one key in Slack':'Incident.'})),
    c('streaming','Streaming','Send tokens as they generate','beginner',6,['azure-ai'],
      'Streaming delivers tokens to clients as they are produced, improving perceived latency and enabling cancelation. Implement with server-sent events or websockets, and design UIs for partial answers.',
      'Reading a story as it’s being typed instead of waiting for the whole novel PDF.',
      ['Model emits tokens incrementally.','API streams to client.','UI renders partial text.','Users can stop early.','Handle disconnects cleanly.'],
      [['SSE','Server-Sent Events'],['Time-to-first-token','Latency until first output'],['Cancelation','Stop generation early']],
      ['Request starts.','First token arrives quickly.','UI updates live.','User stops.','Server cancels generation.'],
      'Chat UIs','Streaming makes tutors feel responsive during long explanations.','Perceived performance matters.',
      [q('Streaming improves…',['Perceived latency','Model truth automatically','GPU silicon','CSS specificity'],0,'UX speed feel.'),q('Time-to-first-token measures…',['Latency to first output','Disk RPM','Font size','Cable ohms'],0,'TTFT.'),q('Cancelation lets users…',['Stop generation early','Delete the cloud','Ban JSON','Skip auth'],0,'Control.')],
      toggle(['Wait for full answer','Stream tokens','No cancel button'],{'Wait for full answer':'Feels slower.','Stream tokens':'Better UX.','No cancel button':'Wasted tokens.'})),
    c('monitoring-basics','Monitoring basics','Watch latency, errors, and cost','beginner',6,['streaming'],
      'Monitoring tracks request rates, latencies, error codes, token usage, and tool failures. Without it, LLM apps fail quietly and bills surprise you. Start with golden signals plus token economics.',
      'A car dashboard: speed, fuel, warning lights—not driving blind.',
      ['Latency and error rate.','Token/cost metrics.','Trace IDs across orchestration.','Alert on budgets.','Dashboards for debugging.'],
      [['Golden signals','Latency, traffic, errors, saturation'],['Trace ID','Correlates logs across steps'],['Token usage','Consumption meter']],
      ['Emit metrics per request.','Dashboard graphs.','Alert on error spikes.','Investigate traces.','Fix and verify.'],
      'Exam-week spike','Latency alerts reveal retrieval bottlenecks under load.','Metrics guide scaling.',
      [q('Monitor especially…',['Latency, errors, token cost','Only wallpaper','Only fan RGB','Only commit emojis'],0,'Golden + cost.'),q('Trace IDs help…',['Correlate multi-step requests','Heat rooms','Bold text','Route HDMI'],0,'Debug.'),q('Cost alerts prevent…',['Bill shock','Better fonts','Shorter cables','Colder coffee automatically'],0,'Budgets.')],
      toggle(['No metrics','Latency/error/token dashboards','Alert on nothing'],{'No metrics':'Blind.','Latency/error/token dashboards':'Minimum viable.','Alert on nothing':'Too late.'})),
  ],

  'production-ai': [
    c('evaluation','Evaluation','Measure quality with tests, not vibes','beginner',8,[],
      'Evaluation scores whether an AI system meets task requirements: automated metrics, LLM-as-judge carefully used, human review, and regression sets. Production teams treat evals like unit tests for behavior.',
      'Exam questions for your product—run them before every release.',
      ['Build a golden dataset.','Score answers automatically where possible.','Sample human reviews.','Run on every prompt/model change.','Separate retrieval vs generation scores for RAG.'],
      [['Golden set','Curated labeled examples'],['Regression eval','Catch quality drops'],['LLM-as-judge','Model scoring outputs with caveats']],
      ['Collect representative cases.','Define rubrics.','Score baseline.','Change a prompt.','Compare deltas.'],
      'Tutor answer quality gates','Weekly eval suite blocks deploys that hurt math accuracy.','Evals are release gates.',
      [q('Evaluation should be…',['Systematic and repeatable','Only vibes','Only GPU temps','Only CSS lint'],0,'Systematic.'),q('Golden sets are…',['Curated test examples','Random memes only','Docker secrets','Fan curves'],0,'Tests.'),q('For RAG, evaluate…',['Retrieval and answers','Only fonts','Only HDMI','Only cables'],0,'Both stages.')],
      toggle(['Ship by intuition','Golden set regressions','One anecdote from a friend'],{'Ship by intuition':'Risky.','Golden set regressions':'Healthy.','One anecdote from a friend':'Anecdote ≠ eval.'})),
    c('observability','Observability','See inside live requests','intermediate',7,['evaluation'],
      'Observability captures traces, logs, and artifacts for each request: prompts, retrieved chunks, tool calls, latencies, and outputs (with privacy controls). It turns “the model was weird” into a debuggable timeline.',
      'Flight data recorders for AI requests.',
      ['Trace orchestration steps.','Redact sensitive fields.','Link metrics to traces.','Sample when volume is huge.','Use traces to improve prompts/RAG.'],
      [['Trace','Structured timeline of a request'],['Span','One step inside a trace'],['Redaction','Remove sensitive data']],
      ['Request starts with trace id.','Retrieval span logs chunk IDs.','LLM span logs token stats.','Tool span logs args/results.','Debug with the timeline.'],
      'Why did it cite the wrong doc?','Trace shows reranker order flipped after a deploy.','Observability finds root causes.',
      [q('Observability provides…',['Debuggable traces of requests','Free GPUs','Perfect truth','Automatic compliance forever'],0,'Visibility.'),q('Redaction is needed because…',['Prompts may contain secrets','Fonts are bold','CSS is pink','HDMI is hot'],0,'Privacy.'),q('Spans represent…',['Steps inside a trace','Ocean waves','Cable types','Mouse LOD'],0,'Steps.')],
      toggle(['Log nothing','Traces with redaction','Log raw secrets forever'],{'Log nothing':'Cannot debug.','Traces with redaction':'Balanced.','Log raw secrets forever':'Breach risk.'})),
    c('security-privacy','Security / Privacy','Threat models for LLM apps','intermediate',8,['observability'],
      'LLM apps add threats: prompt injection, data exfiltration via tools, training data leakage, insecure key handling, and sensitive logs. Apply least privilege, isolation, redaction, and adversarial testing.',
      'A building with doors, badges, cameras, and rules for contractors—not only a polite receptionist.',
      ['Threat-model tools and data flows.','Never trust retrieved/web content as instructions.','Isolate credentials.','Minimize retained personal data.','Pen-test prompts and tools.'],
      [['Prompt injection','Hostile text steering the model'],['Least privilege','Minimal access rights'],['Exfiltration','Stealing data via outputs/tools']],
      ['Map data flows.','Identify injection surfaces.','Constrain tools.','Redact logs.','Test attacks.'],
      'Web-reading agents','Untrusted pages tried to exfiltrate secrets via tool calls.','Isolation saved the day.',
      [q('Prompt injection is…',['Hostile text steering the model','A CSS property','A GPU driver','A vector index type'],0,'Injection.'),q('Tool access should follow…',['Least privilege','Root for all','No auth','Public keys in apps'],0,'Least privilege.'),q('Logs may contain…',['Sensitive prompts needing redaction','Only weather','Only fonts','Only HDMI CEC'],0,'Careful logging.')],
      toggle(['Trust all retrieved text','Isolate tools + sanitize','Put keys in the mobile app'],{'Trust all retrieved text':'Unsafe.','Isolate tools + sanitize':'Hardening.','Put keys in the mobile app':'Leak.'})),
    c('hallucination-mitigation','Hallucination mitigation','Reduce fluent falsehoods','intermediate',7,['security-privacy'],
      'Mitigate hallucinations with grounding (RAG/tools), abstention (“I don’t know”), citation requirements, lower-stakes drafting roles, constrained decoding, and human review for high risk. No single trick eliminates them.',
      'Journalism standards: require sources, allow “unknown,” and fact-check before publish.',
      ['Ground with evidence.','Allow uncertainty.','Cite or link sources.','Verify critical claims.','Measure groundedness.'],
      [['Abstention','Refusing when unsure'],['Citation','Pointer to evidence'],['Fact check','Independent verification']],
      ['Ask a factual question.','Retrieve evidence.','Answer only from evidence.','Cite chunks.','Flag missing evidence.'],
      'Medical adjacent FAQ','Bot refuses diagnosis and cites approved leaflets only.','Scope control reduces harm.',
      [q('A strong mitigation is…',['Grounding plus abstention','Max temperature always','No evals','Delete retrieval'],0,'Ground and abstain.'),q('Citations help users…',['Verify claims','Heat laptops','Bold text','Route packets'],0,'Verify.'),q('Hallucinations can be fully solved by one prompt sentence.',['True','False','Only in Latin','Only offline'],1,'Defense in depth.')],
      toggle(['Always answer confidently','Answer only with citations or abstain','Ban all uncertainty language'],{'Always answer confidently':'Hallucination bait.','Answer only with citations or abstain':'Safer pattern.','Ban all uncertainty language':'Forces guessing.'})),
    c('production-guardrails','Guardrails','Runtime policy enforcement','intermediate',7,['hallucination-mitigation'],
      'Production guardrails enforce policies at runtime: topic blocks, PII filters, tool allowlists, rate limits, and output validators. Layer them: before model, around tools, after generation.',
      'Airport security lanes plus cockpit locks—multiple checkpoints.',
      ['Input filters.','Tool gates.','Output validators.','Rate and abuse limits.','Metrics on blocks.'],
      [['Rate limit','Cap request volume'],['Output validator','Checks format/policy'],['Policy engine','Central rules']],
      ['Input screened.','Model runs.','Output screened.','Tool call gated.','Safe path completes.'],
      'Student data bots','PII filters block national IDs in outputs.','Policy as code.',
      [q('Guardrails should be layered…',['Before, around tools, and after','Only in marketing','Only in CSS','Only on Fridays'],0,'Layers.'),q('Rate limits mitigate…',['Abuse and cost spikes','Hallucinations completely','Need for auth','Need for UX'],0,'Abuse/cost.'),q('Validators check…',['Outputs against rules/schemas','Ocean tides','Fan RGB','Mouse LOD'],0,'Checks.')],
      toggle(['Prompt-only policy','Layered runtime guardrails','Disable all filters in prod'],{'Prompt-only policy':'Soft.','Layered runtime guardrails':'Production grade.','Disable all filters in prod':'Reckless.'})),
    c('cost-optimization','Cost optimization','Spend tokens where they matter','beginner',7,['production-guardrails'],
      'LLM cost is driven by tokens, model choice, retries, and tool calls. Optimize with caching, smaller models for easy tasks, tighter prompts, retrieval over long pastes, and routing hard cases to bigger models.',
      'Household budgeting: stop leaving every light on; use the big oven only when needed.',
      ['Measure cost per successful task.','Cache repeated prompts/results.','Route by difficulty.','Trim context waste.','Cap agent steps.'],
      [['Cache','Reuse prior results'],['Model routing','Pick model by case difficulty'],['Cost per task','Economic KPI']],
      ['Log token spend.','Find verbose prompts.','Tighten and cache.','Route simple intents small.','Bill drops, quality holds.'],
      'Support deflection','FAQ intents use a small model; complex cases escalate.','Routing saves money.',
      [q('Major LLM cost driver is…',['Tokens and model choice','Wallpaper resolution','Cable color','Commit emoji count'],0,'Tokens/models.'),q('Caching helps…',['Repeated work','Guaranteed novelty always','Infinite context','No auth'],0,'Reuse.'),q('Routing sends…',['Hard cases to bigger models','All cases to the largest always','No cases anywhere','Only CSS to GPUs'],0,'Right-size.')],
      toggle(['Largest model for everything','Routed models + cache','Uncapped agent loops'],{'Largest model for everything':'Expensive.','Routed models + cache':'Sane.','Uncapped agent loops':'Bill shock.'})),
    c('latency-scaling','Latency / Scaling','Make it fast enough under load','intermediate',7,['cost-optimization'],
      'Latency comes from retrieval, model time-to-first-token, tool calls, and network hops. Scale with concurrency limits, caches, async jobs, streaming, and horizontal replicas—while watching queueing delays.',
      'Grocery checkout: open more lanes at peak, and let people see items scanned live (streaming).',
      ['Measure p50/p95 latency.','Stream early tokens.','Cache hot retrievals.','Bound concurrency.','Scale replicas carefully.'],
      [['p95 latency','Slowish typical-worse delay'],['Concurrency','Simultaneous in-flight requests'],['Queueing','Wait time under overload']],
      ['Load test starts.','p95 spikes.','Add cache + replicas.','Stream TTFT improves.','SLOs met.'],
      'Exam-week tutor traffic','Caching syllabus chunks keeps RAG snappy.','Scale the bottleneck, not everything.',
      [q('Streaming mainly helps…',['Time-to-first-token UX','Model truth','GPU lithography','CSS grids'],0,'Perceived speed.'),q('p95 focuses on…',['Worse common latency','Best case only','Font size','Cable ohms'],0,'Tail-ish latency.'),q('Under overload, watch…',['Queues and concurrency limits','Only wallpapers','Only emojis','Only HDMI CEC'],0,'Saturation.')],
      toggle(['No load tests','p95 SLOs + streaming + cache','Infinite concurrency'],{'No load tests':'Surprises.','p95 SLOs + streaming + cache':'Solid.','Infinite concurrency':'Meltdown.'})),
    c('reliability','Reliability','Fail gracefully and recover','intermediate',7,['latency-scaling'],
      'Reliable AI systems define timeouts, retries with idempotency, fallbacks (smaller model, cached answer, human), and clear degraded modes. Models will error; products should not hard-crash.',
      'City power grids with backup generators and polite “service degraded” banners.',
      ['Timeouts everywhere.','Retries only when safe.','Fallbacks for outages.','Circuit breakers.','Status communication to users.'],
      [['Fallback','Backup behavior'],['Circuit breaker','Stop calling a sick dependency'],['Degraded mode','Limited but honest functionality']],
      ['Provider outage starts.','Timeouts fire.','Fallback model engages.','User sees degraded notice.','Primary recovers.'],
      'Checkout assistants','If LLM down, show FAQ search fallback.','Degrade, don’t blank-screen.',
      [q('Reliability includes…',['Timeouts, retries, fallbacks','Only happy paths','No monitoring','Infinite waits'],0,'Resilience.'),q('Idempotency matters for…',['Safe retries','Bold fonts','Cool GPUs','Short cables'],0,'Retry safety.'),q('Degraded mode should be…',['Honest and limited','Hidden always','Louder hallucinations','Keyless admin'],0,'Honesty.')],
      toggle(['Crash on provider 500','Fallback + user notice','Silent wrong answers'],{'Crash on provider 500':'Brittle.','Fallback + user notice':'Reliable.','Silent wrong answers':'Worst.'})),
    c('best-practices-checklist','Best practices checklist','A practical ship list','beginner',8,['reliability'],
      'Before calling an AI feature “done,” check: threat model, eval suite, tracing, budgets, guardrails, fallbacks, privacy review, and on-call ownership. This checklist turns Generative AI from a demo into an engineered product.',
      'Preflight checklist before takeoff—not optional theater.',
      ['Define user value and risks.','Evals gate releases.','Observe production.','Control cost and latency.','Own incidents and improvements.'],
      [['Go/no-go','Release readiness decision'],['Owner','Person/team on point'],['SLO','Service level objective']],
      ['Draft checklist.','Score the feature.','Fix gaps.','Ship with owners.','Review after incidents.'],
      'Capstone demos to pilots','Student teams use the checklist before showing faculty advisors.','Discipline beats dazzle.',
      [q('A release checklist should include…',['Evals, safety, observability, owners','Only logos','Only GPU brands','Only emojis'],0,'Readiness.'),q('SLOs help define…',['Reliability targets','Font fashion','Cable taste','Wallpaper art'],0,'Targets.'),q('Demos without owners…',['Become orphan incidents','Are always safe','Need no logs','Never fail'],0,'Ownership matters.')],
      toggle(['Ship demo as prod','Pass checklist with owners','Ignore incidents'],{'Ship demo as prod':'Reckless.','Pass checklist with owners':'Professional.','Ignore incidents':'Culture failure.'})),
  ],
};
